// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: antd/v1/health.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Antd_V1_HealthCheckRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Antd_V1_HealthCheckResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "ok"
  public var status: String = String()

  /// "default", "local", "alpha"
  public var network: String = String()

  /// antd crate version (e.g. "0.4.0")
  public var version: String = String()

  /// EVM preset: "arbitrum-one", "arbitrum-sepolia", "local", "custom"
  public var evmNetwork: String = String()

  /// seconds since process start
  public var uptimeSeconds: UInt64 = 0

  /// short git SHA, or "" if built outside a git checkout
  public var buildCommit: String = String()

  /// token contract, or "" if unconfigured
  public var paymentTokenAddress: String = String()

  /// payment vault contract, or "" if unconfigured
  public var paymentVaultAddress: String = String()

  /// best-effort write-path signal: max(routing_table_size, connected_peers) >= rebootstrap_threshold; false = stores known-degraded
  public var writeReady: Bool = false

  /// live transport-level connection count (distinct from routing_table_size)
  public var connectedPeers: UInt32 = 0

  /// DHT routing-table entries — the number auto-re-bootstrap keys off
  public var routingTableSize: UInt32 = 0

  /// routing-table floor below which the DHT auto-re-bootstraps
  public var rebootstrapThreshold: UInt32 = 0

  /// seconds since the last successful store-type operation; absent if none this process
  public var lastStoreOkSecsAgo: UInt64 {
    get {_lastStoreOkSecsAgo ?? 0}
    set {_lastStoreOkSecsAgo = newValue}
  }
  /// Returns true if `lastStoreOkSecsAgo` has been explicitly set.
  public var hasLastStoreOkSecsAgo: Bool {self._lastStoreOkSecsAgo != nil}
  /// Clears the value of `lastStoreOkSecsAgo`. Subsequent reads from it will return its default value.
  public mutating func clearLastStoreOkSecsAgo() {self._lastStoreOkSecsAgo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _lastStoreOkSecsAgo: UInt64? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "antd.v1"

extension Antd_V1_HealthCheckRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthCheckRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_HealthCheckRequest, rhs: Antd_V1_HealthCheckRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Antd_V1_HealthCheckResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthCheckResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}network\0\u{1}version\0\u{3}evm_network\0\u{3}uptime_seconds\0\u{3}build_commit\0\u{3}payment_token_address\0\u{3}payment_vault_address\0\u{3}write_ready\0\u{3}connected_peers\0\u{3}routing_table_size\0\u{3}rebootstrap_threshold\0\u{3}last_store_ok_secs_ago\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.network) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.evmNetwork) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.uptimeSeconds) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.buildCommit) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.paymentTokenAddress) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.paymentVaultAddress) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.writeReady) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.connectedPeers) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.routingTableSize) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self.rebootstrapThreshold) }()
      case 13: try { try decoder.decodeSingularUInt64Field(value: &self._lastStoreOkSecsAgo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 1)
    }
    if !self.network.isEmpty {
      try visitor.visitSingularStringField(value: self.network, fieldNumber: 2)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 3)
    }
    if !self.evmNetwork.isEmpty {
      try visitor.visitSingularStringField(value: self.evmNetwork, fieldNumber: 4)
    }
    if self.uptimeSeconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.uptimeSeconds, fieldNumber: 5)
    }
    if !self.buildCommit.isEmpty {
      try visitor.visitSingularStringField(value: self.buildCommit, fieldNumber: 6)
    }
    if !self.paymentTokenAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentTokenAddress, fieldNumber: 7)
    }
    if !self.paymentVaultAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.paymentVaultAddress, fieldNumber: 8)
    }
    if self.writeReady != false {
      try visitor.visitSingularBoolField(value: self.writeReady, fieldNumber: 9)
    }
    if self.connectedPeers != 0 {
      try visitor.visitSingularUInt32Field(value: self.connectedPeers, fieldNumber: 10)
    }
    if self.routingTableSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.routingTableSize, fieldNumber: 11)
    }
    if self.rebootstrapThreshold != 0 {
      try visitor.visitSingularUInt32Field(value: self.rebootstrapThreshold, fieldNumber: 12)
    }
    try { if let v = self._lastStoreOkSecsAgo {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Antd_V1_HealthCheckResponse, rhs: Antd_V1_HealthCheckResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.network != rhs.network {return false}
    if lhs.version != rhs.version {return false}
    if lhs.evmNetwork != rhs.evmNetwork {return false}
    if lhs.uptimeSeconds != rhs.uptimeSeconds {return false}
    if lhs.buildCommit != rhs.buildCommit {return false}
    if lhs.paymentTokenAddress != rhs.paymentTokenAddress {return false}
    if lhs.paymentVaultAddress != rhs.paymentVaultAddress {return false}
    if lhs.writeReady != rhs.writeReady {return false}
    if lhs.connectedPeers != rhs.connectedPeers {return false}
    if lhs.routingTableSize != rhs.routingTableSize {return false}
    if lhs.rebootstrapThreshold != rhs.rebootstrapThreshold {return false}
    if lhs._lastStoreOkSecsAgo != rhs._lastStoreOkSecsAgo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
