/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  /** Connect to a local test network (loopback). */
  static connectLocal(dataDir?: string | undefined | null): Promise<Client>
  /**
   * Connect using explicit bootstrap peers (`/ip4/<ip>/udp/<port>/quic`
   * multiaddr strings). Read-only; use a wallet/external-signer variant to
   * write.
   */
  static connect(peers: Array<string>, dataDir?: string | undefined | null): Promise<Client>
  /**
   * Connect to the Autonomi **production network** using the SDK's vendored
   * bootstrap peers — no configuration. Read-only.
   */
  static connectDefault(dataDir?: string | undefined | null): Promise<Client>
  /**
   * `connectDefault` with a wallet attached for writes, preset for the
   * production EVM network.
   */
  static connectDefaultWithWallet(privateKey: string, dataDir?: string | undefined | null): Promise<Client>
  /**
   * `connectDefault` configured for the **external-signer** flow (mobile
   * wallets / WalletConnect): production peers + EVM network for quotes, no
   * wallet attached.
   */
  static connectDefaultForExternalSigner(dataDir?: string | undefined | null): Promise<Client>
  /** Connect with a wallet configured for writes on a custom EVM network. */
  static connectWithWallet(peers: Array<string>, privateKey: string, rpcUrl: string, paymentTokenAddress: string, paymentVaultAddress: string, dataDir?: string | undefined | null): Promise<Client>
  /**
   * Connect to a local devnet described by a devnet manifest JSON file (the
   * file written by `ant-devnet`). **Development/testing only.** Fails if the
   * manifest is missing, malformed, or has no `evm` section.
   */
  static connectFromDevnetManifest(manifestPath: string, dataDir?: string | undefined | null): Promise<Client>
  /**
   * Like `connectFromDevnetManifest` but for the **external-signer** flow:
   * configures the devnet EVM network for quotes but attaches no wallet.
   */
  static connectFromDevnetManifestExternalSigner(manifestPath: string, dataDir?: string | undefined | null): Promise<Client>
  /**
   * Connect with an EVM network configured but **no wallet** — the
   * external-signer entry point. Quote/price queries work; payment is signed
   * off-device. Pay via `prepare*` + your signer + `finalize*`.
   */
  static connectForExternalSigner(peers: Array<string>, rpcUrl: string, paymentTokenAddress: string, paymentVaultAddress: string, dataDir?: string | undefined | null): Promise<Client>
  /** Store a single chunk on the network. */
  chunkPut(data: Uint8Array): Promise<ChunkPutResult>
  /** Retrieve a chunk by hex-encoded address. */
  chunkGet(addressHex: string): Promise<Buffer>
  /** Check whether a chunk exists on the network. */
  chunkExists(addressHex: string): Promise<boolean>
  /** Upload data publicly (retrievable by the returned address). */
  dataPutPublic(data: Uint8Array, paymentMode: PaymentMode): Promise<DataPutPublicResult>
  /** Retrieve public data by its hex-encoded data-map address. */
  dataGetPublic(addressHex: string): Promise<Buffer>
  /**
   * Upload data privately. Returns the serialized data map (hex) — keep it
   * secret; it is required to retrieve the data.
   */
  dataPutPrivate(data: Uint8Array, paymentMode: PaymentMode): Promise<DataPutPrivateResult>
  /** Retrieve private data using a hex-encoded data map. */
  dataGetPrivate(dataMapHex: string): Promise<Buffer>
  /**
   * Upload a file from disk publicly. Returns the shareable address plus
   * chunk/cost details.
   */
  fileUploadPublic(path: string, paymentMode: PaymentMode): Promise<FilePutPublicResult>
  /** `fileUploadPublic` with live progress (`Encrypting`/`Quoting`/`Storing`). */
  fileUploadPublicWithProgress(path: string, paymentMode: PaymentMode, onProgress: (progress: ProgressUpdate) => void): Promise<FilePutPublicResult>
  /**
   * Upload a file from disk privately. Returns the serialized data map (hex);
   * keep it secret to retrieve the file later.
   */
  fileUploadPrivate(path: string, paymentMode: PaymentMode): Promise<FilePutPrivateResult>
  /** `fileUploadPrivate` with live progress. */
  fileUploadPrivateWithProgress(path: string, paymentMode: PaymentMode, onProgress: (progress: ProgressUpdate) => void): Promise<FilePutPrivateResult>
  /** Download a public file to disk by hex-encoded address. */
  fileDownloadPublic(addressHex: string, destPath: string): Promise<void>
  /** Download a private file to disk by hex-encoded data map. */
  fileDownloadPrivate(dataMapHex: string, destPath: string): Promise<void>
  /**
   * Publish an existing private data map (hex) as a public network chunk,
   * returning its hex address — without re-uploading the underlying data.
   */
  dataMapStore(dataMapHex: string): Promise<string>
  /**
   * Fetch a public data map by hex address and return it serialized (hex) —
   * the inverse of `dataMapStore`.
   */
  dataMapFetch(addressHex: string): Promise<string>
  /**
   * Estimate the cost of uploading a file *before* preparing or paying.
   * Samples a few chunk addresses; fast and needs no wallet. Check
   * `CostEstimate.confidence` before treating a `"0"` cost as free.
   */
  estimateFileCost(path: string, paymentMode: PaymentMode): Promise<CostEstimate>
  /** `estimateFileCost` with live progress (the `Encrypting` phase). */
  estimateFileCostWithProgress(path: string, paymentMode: PaymentMode, onProgress: (progress: ProgressUpdate) => void): Promise<CostEstimate>
  /** Approve token spend for storage payments (one-time; wallet-backed client). */
  walletApprove(): Promise<void>
  /**
   * Phase 1: encrypt `data`, collect quotes, and return the payment summary.
   * The prepared state is retained under the returned `uploadId` until finalize.
   */
  prepareDataUpload(data: Uint8Array, visibility: Visibility): Promise<PreparedUploadInfo>
  /** Phase 1 for a file on disk. */
  prepareFileUpload(path: string, visibility: Visibility): Promise<PreparedUploadInfo>
  /** Phase 1 for a file, with encryption/quoting progress. */
  prepareFileUploadWithProgress(path: string, visibility: Visibility, onProgress: (progress: ProgressUpdate) => void): Promise<PreparedUploadInfo>
  /**
   * Phase 1.5: build the ordered transactions (ERC-20 `approve` + vault
   * payment call(s)) the external wallet must sign to pay for a prepared
   * upload. Empty when everything was already stored.
   */
  paymentTransactions(uploadId: string): Promise<Array<TxRequest>>
  /**
   * Phase 2 (wave-batch): after the wallet has paid, finalize by supplying the
   * `quoteHash -> txHash` map (both 0x-prefixed hex). Pass an empty map if
   * everything was already stored.
   */
  finalizeUpload(uploadId: string, txHashes: Record<string, string>): Promise<ExternalUploadResult>
  /** `finalizeUpload` with live storing progress. */
  finalizeUploadWithProgress(uploadId: string, txHashes: Record<string, string>, onProgress: (progress: ProgressUpdate) => void): Promise<ExternalUploadResult>
  /**
   * Phase 2 (merkle): finalize by supplying the `winnerPoolHash` read from the
   * `MerklePaymentMade` event (see the `merkleWinnerPoolHash` free function).
   */
  finalizeUploadMerkle(uploadId: string, winnerPoolHash: string): Promise<ExternalUploadResult>
  /** `finalizeUploadMerkle` with live storing progress. */
  finalizeUploadMerkleWithProgress(uploadId: string, winnerPoolHash: string, onProgress: (progress: ProgressUpdate) => void): Promise<ExternalUploadResult>
  /**
   * Discard a prepared upload that will not be finalized, freeing the chunk
   * content it holds in memory. Returns `true` if an upload with this id was
   * present. Safe to call with an unknown/already-finalized id.
   */
  cancelUpload(uploadId: string): boolean
  /**
   * Download public data by address straight to a file on disk, reporting
   * live progress (`Resolving` then `Downloading`). Returns bytes written.
   */
  downloadPublicToFile(addressHex: string, destPath: string, onProgress: (progress: ProgressUpdate) => void): Promise<number>
  /**
   * Download private data by hex-encoded data map straight to a file on disk,
   * reporting live progress. Returns bytes written.
   */
  downloadPrivateToFile(dataMapHex: string, destPath: string, onProgress: (progress: ProgressUpdate) => void): Promise<number>
}

export declare class Wallet {
  /**
   * Create a wallet from an EVM private key on a custom network (RPC URL +
   * token/vault contract addresses). The private key is zeroized inside the
   * core as soon as the wallet is built.
   */
  static fromPrivateKey(privateKey: string, rpcUrl: string, paymentTokenAddress: string, paymentVaultAddress: string): Wallet
  /** The wallet's public address (0x-prefixed hex). */
  address(): string
  /** Token balance in atto-tokens (base-10 string). */
  balanceOfTokens(): Promise<string>
  /** Gas-token balance in wei (base-10 string). */
  balanceOfGasTokens(): Promise<string>
}

/**
 * **Test hook — not part of the public API.** Fires `ticks` synthetic
 * `Encrypting` progress updates through the same bridge every `*WithProgress`
 * method uses, from a background thread, then resolves. Exists so the
 * callback-exception containment (a throwing `onProgress` becomes an
 * `AntProgressCallbackError` warning, never a fatal exception) has an offline
 * regression test.
 */
export declare function _emitProgressForTest(onProgress: (progress: ProgressUpdate) => void, ticks: number): Promise<void>

/**
 * The AntFfi SDK version (e.g. `"0.0.8"`) — matches the released SDK version
 * shared across all bindings.
 */
export declare function antFfiVersion(): string

/** One candidate node inside a [`PoolCommitmentEntry`]. */
export interface CandidateNodeEntry {
  /** 0x-prefixed EVM rewards address (20 bytes). */
  rewardsAddress: string
  /** Node price in atto-tokens (base-10 string). */
  amount: string
}

/** Result of storing a single chunk on the network. */
export interface ChunkPutResult {
  /** Hex-encoded chunk address (32 bytes). */
  address: string
}

/** How much to trust a [`CostEstimate`]'s `storageCostAtto`. */
export declare enum CostConfidence {
  /** Extrapolated from at least one live quote (the normal case). */
  PricedSample = 0,
  /** Every chunk was sampled and already stored; cost is exactly `"0"`. */
  VerifiedAllAlreadyStored = 1,
  /**
   * Every *sampled* chunk was already stored but the tail was unsampled;
   * `"0"` is a best-effort guess. Render as "likely already stored".
   */
  AllSamplesAlreadyStoredIncomplete = 2
}

/**
 * Estimated cost of uploading a file, produced *before* any payment by
 * sampling a few of the file's chunk addresses. No wallet required.
 */
export interface CostEstimate {
  /** Original file size in bytes. */
  fileSize: number
  /**
   * Number of data chunks the file would split into (excludes the extra
   * data-map chunk added for public uploads).
   */
  chunkCount: number
  /** Estimated storage cost in atto-tokens (base-10 string; may exceed u64). */
  storageCostAtto: string
  /**
   * Rough estimated gas cost in wei (base-10 string). A heuristic, NOT a live
   * gas-price query.
   */
  estimatedGasCostWei: string
  /** Payment mode that would be used. */
  paymentMode: PaymentMode
  /**
   * How much to trust `storageCostAtto` — check before treating a `"0"` cost
   * as free.
   */
  confidence: CostConfidence
}

/** Result of a private data upload (data map returned to caller, kept secret). */
export interface DataPutPrivateResult {
  /** Hex-encoded serialized data map (caller keeps this secret). */
  dataMap: string
  /** Number of chunks stored. */
  chunksStored: number
  /** Payment mode that was used. */
  paymentModeUsed: PaymentMode
}

/** Result of a public data upload (data map stored as a public chunk). */
export interface DataPutPublicResult {
  /** Hex-encoded address of the stored data map. */
  address: string
  /** Number of chunks stored. */
  chunksStored: number
  /** Payment mode that was used. */
  paymentModeUsed: PaymentMode
}

/** Result of finalizing an external-signer upload. */
export interface ExternalUploadResult {
  /** Hex-encoded serialized data map (for private retrieval; always present). */
  dataMap: string
  /** For public uploads: hex data-map address (shareable). Absent if private. */
  address?: string
  /** Number of chunks stored on the network. */
  chunksStored: number
  /** Total storage cost paid, in atto-tokens (base-10). "0" if all pre-existed. */
  storageCostAtto: string
  /** Total gas cost in wei (base-10). */
  gasCostWei: string
}

/**
 * Result of uploading a private file. Keep `dataMap` secret — it is required
 * to retrieve the file and is not recoverable from the network.
 */
export interface FilePutPrivateResult {
  /** Hex-encoded serialized data map (caller keeps this secret). */
  dataMap: string
  /** Number of chunks stored on the network. */
  chunksStored: number
  /** Total storage cost paid, in atto-tokens (base-10). "0" if all pre-existed. */
  storageCostAtto: string
  /** Total gas cost in wei (base-10). */
  gasCostWei: string
  /** Payment mode that was used. */
  paymentModeUsed: PaymentMode
}

/** Result of uploading a public file. */
export interface FilePutPublicResult {
  /** Hex-encoded address of the stored data map. */
  address: string
  /** Number of chunks stored on the network. */
  chunksStored: number
  /** Total storage cost paid, in atto-tokens (base-10). "0" if all pre-existed. */
  storageCostAtto: string
  /** Total gas cost in wei (base-10). */
  gasCostWei: string
  /** Payment mode that was used. */
  paymentModeUsed: PaymentMode
}

/**
 * Read the winning pool hash from a settled `payForMerkleTree` transaction (the
 * `MerklePaymentMade` log emitted by `vaultAddress`), 0x-prefixed — pass it to
 * `client.finalizeUploadMerkle`.
 */
export declare function merkleWinnerPoolHash(rpcUrl: string, vaultAddress: string, txHash: string): Promise<string>

/**
 * On-chain configuration for a known Autonomi EVM network. `name` is one of
 * `"arbitrum-one"` / `"arbitrum-sepolia-test"` (and their short aliases).
 */
export declare function networkInfo(name: string): NetworkInfo

/** On-chain configuration for a known Autonomi EVM network. */
export interface NetworkInfo {
  /** EVM chain id (e.g. 42161 Arbitrum One, 421614 Arbitrum Sepolia). */
  chainId: number
  /** 0x-prefixed ANT payment-token address. */
  tokenAddress: string
  /** 0x-prefixed payment-vault address. */
  vaultAddress: string
  /** Default HTTPS RPC URL for the network. */
  rpcUrl: string
}

/** A single on-chain payment the external wallet must settle. */
export interface PaymentEntry {
  /** 0x-prefixed quote hash (32 bytes) — the key in the tx-hash map at finalize. */
  quoteHash: string
  /** 0x-prefixed EVM rewards address to pay. */
  rewardsAddress: string
  /** Amount to pay in atto-tokens (base-10 string; exceeds u64). */
  amount: string
}

/** How an upload is paid for. */
export declare enum PaymentMode {
  /** Let the SDK pick: merkle batching for large uploads, single otherwise. */
  Auto = 0,
  /** Merkle-batched payment — one on-chain payment covering many chunks. */
  Merkle = 1,
  /** Per-quote wave payment. */
  Single = 2
}

/**
 * Payment shape of a prepared external-signer upload — selects which finalize
 * call to use (see [`PreparedUploadInfo`]).
 */
export declare enum PaymentType {
  WaveBatch = 0,
  Merkle = 1
}

/** One pool commitment for the merkle payment call. */
export interface PoolCommitmentEntry {
  /** 0x-prefixed pool hash (32 bytes). */
  poolHash: string
  /** The pool's candidate nodes. */
  candidates: Array<CandidateNodeEntry>
}

/**
 * Summary of a prepared external-signer upload. `paymentType` selects which
 * fields are meaningful and which finalize call to use (see the client's
 * `paymentTransactions` / `finalizeUpload*` docs).
 */
export interface PreparedUploadInfo {
  /** Opaque handle for this prepared upload; pass to the matching finalize call. */
  uploadId: string
  /** Payment shape — selects the finalize call. */
  paymentType: PaymentType
  /**
   * Wave-batch only: per-quote payments to settle on-chain. Empty for merkle
   * or if everything was already stored.
   */
  payments: Array<PaymentEntry>
  /** Wave-batch: total across all payments (atto-tokens, base-10). `"0"` for merkle. */
  totalAmount: string
  /** Merkle only: merkle tree depth for the `payForMerkleTree` call. 0 for wave-batch. */
  depth: number
  /** Merkle only: pool commitments for the `payForMerkleTree` call. Empty for wave-batch. */
  poolCommitments: Array<PoolCommitmentEntry>
  /** Merkle only: timestamp for the `payForMerkleTree` call. 0 for wave-batch. */
  merklePaymentTimestamp: number
  /**
   * For public uploads: hex address the data is retrievable from after
   * finalize. Absent for private uploads.
   */
  dataMapAddress?: string
  /** True if every chunk already existed on the network — nothing to pay. */
  alreadyStored: boolean
}

/** Which phase a [`ProgressUpdate`] belongs to. */
export declare enum ProgressPhase {
  Encrypting = 0,
  Quoting = 1,
  Storing = 2,
  Resolving = 3,
  Downloading = 4
}

/**
 * A progress update for a long-running upload or download. `total` is 0 when
 * unknown yet (show an indeterminate bar); otherwise `done / total` is a 0..1
 * fraction of the current phase.
 */
export interface ProgressUpdate {
  phase: ProgressPhase
  done: number
  total: number
}

/** What a [`TxRequest`] is for. */
export declare enum TxKind {
  /** ERC-20 allowance approval (sent to the token contract). */
  Approve = 0,
  /** The vault payment call. */
  Pay = 1
}

/** Outcome of a settled transaction, from `waitForReceipt`. */
export interface TxReceipt {
  /** `true` if the transaction succeeded (receipt status `0x1`). */
  success: boolean
  /** Gas units consumed (base-10 string). */
  gasUsed: string
  /** Effective gas price paid in wei (base-10 string). */
  effectiveGasPrice: string
}

/**
 * One transaction the external wallet must sign & send, in order, to pay for a
 * prepared upload (produced by `client.paymentTransactions`).
 */
export interface TxRequest {
  /** 0x-prefixed contract address to send the transaction to. */
  to: string
  /** 0x-prefixed ABI-encoded calldata for the transaction's `data` field. */
  data: string
  /** What this transaction is for (allowance approval vs the payment call). */
  kind: TxKind
  /**
   * Wave-batch `Pay` only: the 0x-prefixed quote hashes this payment settles.
   * Map each to the resulting tx hash to build the `finalizeUpload` map.
   */
  quoteHashes: Array<string>
}

/**
 * Whether an upload is publicly retrievable by address, or private (the data
 * map is returned to the caller only).
 */
export declare enum Visibility {
  Public = 0,
  Private = 1
}

/**
 * Poll `rpcUrl` for the receipt of `txHash`, resolving once it's mined (or
 * rejecting on revert / after `timeoutSecs`). Moves the app's hand-rolled
 * `eth_getTransactionReceipt` polling loop into the SDK.
 */
export declare function waitForReceipt(rpcUrl: string, txHash: string, timeoutSecs: number): Promise<TxReceipt>
