# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ntd/v1/data.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"\'\n\x14GetPublicDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"%\n\x15GetPublicDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x14PutPublicDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"E\n\x15PutPublicDataResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"*\n\x17StreamPublicDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x19\n\tDataChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\")\n\x15GetPrivateDataRequest\x12\x10\n\x08\x64\x61ta_map\x18\x01 \x01(\t\"&\n\x16GetPrivateDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x15PutPrivateDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"G\n\x16PutPrivateDataResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x10\n\x08\x64\x61ta_map\x18\x02 \x01(\t\"\x1f\n\x0f\x44\x61taCostRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xbf\x03\n\x0b\x44\x61taService\x12J\n\tGetPublic\x12\x1d.antd.v1.GetPublicDataRequest\x1a\x1e.antd.v1.GetPublicDataResponse\x12J\n\tPutPublic\x12\x1d.antd.v1.PutPublicDataRequest\x1a\x1e.antd.v1.PutPublicDataResponse\x12\x46\n\x0cStreamPublic\x12 .antd.v1.StreamPublicDataRequest\x1a\x12.antd.v1.DataChunk0\x01\x12M\n\nGetPrivate\x12\x1e.antd.v1.GetPrivateDataRequest\x1a\x1f.antd.v1.GetPrivateDataResponse\x12M\n\nPutPrivate\x12\x1e.antd.v1.PutPrivateDataRequest\x1a\x1f.antd.v1.PutPrivateDataResponse\x12\x32\n\x07GetCost\x12\x18.antd.v1.DataCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETPUBLICDATAREQUEST']._serialized_start=53
  _globals['_GETPUBLICDATAREQUEST']._serialized_end=92
  _globals['_GETPUBLICDATARESPONSE']._serialized_start=94
  _globals['_GETPUBLICDATARESPONSE']._serialized_end=131
  _globals['_PUTPUBLICDATAREQUEST']._serialized_start=133
  _globals['_PUTPUBLICDATAREQUEST']._serialized_end=169
  _globals['_PUTPUBLICDATARESPONSE']._serialized_start=171
  _globals['_PUTPUBLICDATARESPONSE']._serialized_end=240
  _globals['_STREAMPUBLICDATAREQUEST']._serialized_start=242
  _globals['_STREAMPUBLICDATAREQUEST']._serialized_end=284
  _globals['_DATACHUNK']._serialized_start=286
  _globals['_DATACHUNK']._serialized_end=311
  _globals['_GETPRIVATEDATAREQUEST']._serialized_start=313
  _globals['_GETPRIVATEDATAREQUEST']._serialized_end=354
  _globals['_GETPRIVATEDATARESPONSE']._serialized_start=356
  _globals['_GETPRIVATEDATARESPONSE']._serialized_end=394
  _globals['_PUTPRIVATEDATAREQUEST']._serialized_start=396
  _globals['_PUTPRIVATEDATAREQUEST']._serialized_end=433
  _globals['_PUTPRIVATEDATARESPONSE']._serialized_start=435
  _globals['_PUTPRIVATEDATARESPONSE']._serialized_end=506
  _globals['_DATACOSTREQUEST']._serialized_start=508
  _globals['_DATACOSTREQUEST']._serialized_end=539
  _globals['_DATASERVICE']._serialized_start=542
  _globals['_DATASERVICE']._serialized_end=989
# @@protoc_insertion_point(module_scope)
