# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/files.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/files.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61ntd/v1/files.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"!\n\x11UploadFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"D\n\x14UploadPublicResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\";\n\x15\x44ownloadPublicRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\tdest_path\x18\x02 \x01(\t\"\x12\n\x10\x44ownloadResponse\"$\n\x11\x41rchiveGetRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"^\n\x0c\x41rchiveEntry\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x04\x12\x10\n\x08modified\x18\x04 \x01(\x04\x12\x0c\n\x04size\x18\x05 \x01(\x04\"<\n\x12\x41rchiveGetResponse\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.antd.v1.ArchiveEntry\";\n\x11\x41rchivePutRequest\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.antd.v1.ArchiveEntry\"B\n\x12\x41rchivePutResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"K\n\x0f\x46ileCostRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x12\x17\n\x0finclude_archive\x18\x03 \x01(\x08\x32\x95\x04\n\x0b\x46ileService\x12I\n\x0cUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12K\n\x0e\x44ownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x12L\n\x0f\x44irUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12N\n\x11\x44irDownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x12K\n\x10\x41rchiveGetPublic\x12\x1a.antd.v1.ArchiveGetRequest\x1a\x1b.antd.v1.ArchiveGetResponse\x12K\n\x10\x41rchivePutPublic\x12\x1a.antd.v1.ArchivePutRequest\x1a\x1b.antd.v1.ArchivePutResponse\x12\x36\n\x0bGetFileCost\x12\x18.antd.v1.FileCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.files_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_UPLOADFILEREQUEST']._serialized_start=54
  _globals['_UPLOADFILEREQUEST']._serialized_end=87
  _globals['_UPLOADPUBLICRESPONSE']._serialized_start=89
  _globals['_UPLOADPUBLICRESPONSE']._serialized_end=157
  _globals['_DOWNLOADPUBLICREQUEST']._serialized_start=159
  _globals['_DOWNLOADPUBLICREQUEST']._serialized_end=218
  _globals['_DOWNLOADRESPONSE']._serialized_start=220
  _globals['_DOWNLOADRESPONSE']._serialized_end=238
  _globals['_ARCHIVEGETREQUEST']._serialized_start=240
  _globals['_ARCHIVEGETREQUEST']._serialized_end=276
  _globals['_ARCHIVEENTRY']._serialized_start=278
  _globals['_ARCHIVEENTRY']._serialized_end=372
  _globals['_ARCHIVEGETRESPONSE']._serialized_start=374
  _globals['_ARCHIVEGETRESPONSE']._serialized_end=434
  _globals['_ARCHIVEPUTREQUEST']._serialized_start=436
  _globals['_ARCHIVEPUTREQUEST']._serialized_end=495
  _globals['_ARCHIVEPUTRESPONSE']._serialized_start=497
  _globals['_ARCHIVEPUTRESPONSE']._serialized_end=563
  _globals['_FILECOSTREQUEST']._serialized_start=565
  _globals['_FILECOSTREQUEST']._serialized_end=640
  _globals['_FILESERVICE']._serialized_start=643
  _globals['_FILESERVICE']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
