# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2
from antd._proto.antd.v1 import graph_pb2 as antd_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/antd.v1.GraphService/Get',
                request_serializer=antd_dot_v1_dot_graph__pb2.GetGraphEntryRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_graph__pb2.GetGraphEntryResponse.FromString,
                _registered_method=True)
        self.CheckExistence = channel.unary_unary(
                '/antd.v1.GraphService/CheckExistence',
                request_serializer=antd_dot_v1_dot_graph__pb2.CheckGraphEntryRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_graph__pb2.GraphExistsResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/antd.v1.GraphService/Put',
                request_serializer=antd_dot_v1_dot_graph__pb2.PutGraphEntryRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_graph__pb2.PutGraphEntryResponse.FromString,
                _registered_method=True)
        self.GetCost = channel.unary_unary(
                '/antd.v1.GraphService/GetCost',
                request_serializer=antd_dot_v1_dot_graph__pb2.GraphEntryCostRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_common__pb2.Cost.FromString,
                _registered_method=True)


class GraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExistence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=antd_dot_v1_dot_graph__pb2.GetGraphEntryRequest.FromString,
                    response_serializer=antd_dot_v1_dot_graph__pb2.GetGraphEntryResponse.SerializeToString,
            ),
            'CheckExistence': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExistence,
                    request_deserializer=antd_dot_v1_dot_graph__pb2.CheckGraphEntryRequest.FromString,
                    response_serializer=antd_dot_v1_dot_graph__pb2.GraphExistsResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=antd_dot_v1_dot_graph__pb2.PutGraphEntryRequest.FromString,
                    response_serializer=antd_dot_v1_dot_graph__pb2.PutGraphEntryResponse.SerializeToString,
            ),
            'GetCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCost,
                    request_deserializer=antd_dot_v1_dot_graph__pb2.GraphEntryCostRequest.FromString,
                    response_serializer=antd_dot_v1_dot_common__pb2.Cost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.GraphService/Get',
            antd_dot_v1_dot_graph__pb2.GetGraphEntryRequest.SerializeToString,
            antd_dot_v1_dot_graph__pb2.GetGraphEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckExistence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.GraphService/CheckExistence',
            antd_dot_v1_dot_graph__pb2.CheckGraphEntryRequest.SerializeToString,
            antd_dot_v1_dot_graph__pb2.GraphExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.GraphService/Put',
            antd_dot_v1_dot_graph__pb2.PutGraphEntryRequest.SerializeToString,
            antd_dot_v1_dot_graph__pb2.PutGraphEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.GraphService/GetCost',
            antd_dot_v1_dot_graph__pb2.GraphEntryCostRequest.SerializeToString,
            antd_dot_v1_dot_common__pb2.Cost.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
