# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61ntd/v1/graph.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"\'\n\x14GetGraphEntryRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"w\n\x15GetGraphEntryResponse\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0f\n\x07parents\x18\x02 \x03(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12-\n\x0b\x64\x65scendants\x18\x04 \x03(\x0b\x32\x18.antd.v1.GraphDescendant\")\n\x16\x43heckGraphEntryRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"%\n\x13GraphExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\x81\x01\n\x14PutGraphEntryRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12\x0f\n\x07parents\x18\x02 \x03(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12-\n\x0b\x64\x65scendants\x18\x04 \x03(\x0b\x32\x18.antd.v1.GraphDescendant\"E\n\x15PutGraphEntryResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"+\n\x15GraphEntryCostRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t2\xa5\x02\n\x0cGraphService\x12\x44\n\x03Get\x12\x1d.antd.v1.GetGraphEntryRequest\x1a\x1e.antd.v1.GetGraphEntryResponse\x12O\n\x0e\x43heckExistence\x12\x1f.antd.v1.CheckGraphEntryRequest\x1a\x1c.antd.v1.GraphExistsResponse\x12\x44\n\x03Put\x12\x1d.antd.v1.PutGraphEntryRequest\x1a\x1e.antd.v1.PutGraphEntryResponse\x12\x38\n\x07GetCost\x12\x1e.antd.v1.GraphEntryCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd._proto.antd._proto.antd.v1.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETGRAPHENTRYREQUEST']._serialized_start=54
  _globals['_GETGRAPHENTRYREQUEST']._serialized_end=93
  _globals['_GETGRAPHENTRYRESPONSE']._serialized_start=95
  _globals['_GETGRAPHENTRYRESPONSE']._serialized_end=214
  _globals['_CHECKGRAPHENTRYREQUEST']._serialized_start=216
  _globals['_CHECKGRAPHENTRYREQUEST']._serialized_end=257
  _globals['_GRAPHEXISTSRESPONSE']._serialized_start=259
  _globals['_GRAPHEXISTSRESPONSE']._serialized_end=296
  _globals['_PUTGRAPHENTRYREQUEST']._serialized_start=299
  _globals['_PUTGRAPHENTRYREQUEST']._serialized_end=428
  _globals['_PUTGRAPHENTRYRESPONSE']._serialized_start=430
  _globals['_PUTGRAPHENTRYRESPONSE']._serialized_end=499
  _globals['_GRAPHENTRYCOSTREQUEST']._serialized_start=501
  _globals['_GRAPHENTRYCOSTREQUEST']._serialized_end=544
  _globals['_GRAPHSERVICE']._serialized_start=547
  _globals['_GRAPHSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
