# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/pointers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/pointers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ntd/v1/pointers.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"$\n\x11GetPointerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"m\n\x12GetPointerResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x04\x12&\n\x06target\x18\x04 \x01(\x0b\x32\x16.antd.v1.PointerTarget\"&\n\x13\x43heckPointerRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\" \n\x0e\x45xistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"X\n\x14\x43reatePointerRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12&\n\x06target\x18\x02 \x01(\x0b\x32\x16.antd.v1.PointerTarget\"E\n\x15\x43reatePointerResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"X\n\x14UpdatePointerRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12&\n\x06target\x18\x02 \x01(\x0b\x32\x16.antd.v1.PointerTarget\"\x17\n\x15UpdatePointerResponse\"(\n\x12PointerCostRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t2\xe2\x02\n\x0ePointerService\x12>\n\x03Get\x12\x1a.antd.v1.GetPointerRequest\x1a\x1b.antd.v1.GetPointerResponse\x12G\n\x0e\x43heckExistence\x12\x1c.antd.v1.CheckPointerRequest\x1a\x17.antd.v1.ExistsResponse\x12G\n\x06\x43reate\x12\x1d.antd.v1.CreatePointerRequest\x1a\x1e.antd.v1.CreatePointerResponse\x12G\n\x06Update\x12\x1d.antd.v1.UpdatePointerRequest\x1a\x1e.antd.v1.UpdatePointerResponse\x12\x35\n\x07GetCost\x12\x1b.antd.v1.PointerCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.pointers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETPOINTERREQUEST']._serialized_start=57
  _globals['_GETPOINTERREQUEST']._serialized_end=93
  _globals['_GETPOINTERRESPONSE']._serialized_start=95
  _globals['_GETPOINTERRESPONSE']._serialized_end=204
  _globals['_CHECKPOINTERREQUEST']._serialized_start=206
  _globals['_CHECKPOINTERREQUEST']._serialized_end=244
  _globals['_EXISTSRESPONSE']._serialized_start=246
  _globals['_EXISTSRESPONSE']._serialized_end=278
  _globals['_CREATEPOINTERREQUEST']._serialized_start=280
  _globals['_CREATEPOINTERREQUEST']._serialized_end=368
  _globals['_CREATEPOINTERRESPONSE']._serialized_start=370
  _globals['_CREATEPOINTERRESPONSE']._serialized_end=439
  _globals['_UPDATEPOINTERREQUEST']._serialized_start=441
  _globals['_UPDATEPOINTERREQUEST']._serialized_end=529
  _globals['_UPDATEPOINTERRESPONSE']._serialized_start=531
  _globals['_UPDATEPOINTERRESPONSE']._serialized_end=554
  _globals['_POINTERCOSTREQUEST']._serialized_start=556
  _globals['_POINTERCOSTREQUEST']._serialized_end=596
  _globals['_POINTERSERVICE']._serialized_start=599
  _globals['_POINTERSERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
