# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/registers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/registers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61ntd/v1/registers.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"%\n\x12GetRegisterRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"$\n\x13GetRegisterResponse\x12\r\n\x05value\x18\x01 \x01(\t\"H\n\x15\x43reateRegisterRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12\x15\n\rinitial_value\x18\x02 \x01(\t\"F\n\x16\x43reateRegisterResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"D\n\x15UpdateRegisterRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12\x11\n\tnew_value\x18\x02 \x01(\t\"5\n\x16UpdateRegisterResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\")\n\x13RegisterCostRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t2\xa1\x02\n\x0fRegisterService\x12@\n\x03Get\x12\x1b.antd.v1.GetRegisterRequest\x1a\x1c.antd.v1.GetRegisterResponse\x12I\n\x06\x43reate\x12\x1e.antd.v1.CreateRegisterRequest\x1a\x1f.antd.v1.CreateRegisterResponse\x12I\n\x06Update\x12\x1e.antd.v1.UpdateRegisterRequest\x1a\x1f.antd.v1.UpdateRegisterResponse\x12\x36\n\x07GetCost\x12\x1c.antd.v1.RegisterCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.registers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETREGISTERREQUEST']._serialized_start=58
  _globals['_GETREGISTERREQUEST']._serialized_end=95
  _globals['_GETREGISTERRESPONSE']._serialized_start=97
  _globals['_GETREGISTERRESPONSE']._serialized_end=133
  _globals['_CREATEREGISTERREQUEST']._serialized_start=135
  _globals['_CREATEREGISTERREQUEST']._serialized_end=207
  _globals['_CREATEREGISTERRESPONSE']._serialized_start=209
  _globals['_CREATEREGISTERRESPONSE']._serialized_end=279
  _globals['_UPDATEREGISTERREQUEST']._serialized_start=281
  _globals['_UPDATEREGISTERREQUEST']._serialized_end=349
  _globals['_UPDATEREGISTERRESPONSE']._serialized_start=351
  _globals['_UPDATEREGISTERRESPONSE']._serialized_end=404
  _globals['_REGISTERCOSTREQUEST']._serialized_start=406
  _globals['_REGISTERCOSTREQUEST']._serialized_end=447
  _globals['_REGISTERSERVICE']._serialized_start=450
  _globals['_REGISTERSERVICE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
