# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2
from antd._proto.antd.v1 import scratchpads_pb2 as antd_dot_v1_dot_scratchpads__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in antd/v1/scratchpads_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScratchpadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/antd.v1.ScratchpadService/Get',
                request_serializer=antd_dot_v1_dot_scratchpads__pb2.GetScratchpadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_scratchpads__pb2.GetScratchpadResponse.FromString,
                _registered_method=True)
        self.CheckExistence = channel.unary_unary(
                '/antd.v1.ScratchpadService/CheckExistence',
                request_serializer=antd_dot_v1_dot_scratchpads__pb2.CheckScratchpadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_scratchpads__pb2.ScratchpadExistsResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/antd.v1.ScratchpadService/Create',
                request_serializer=antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/antd.v1.ScratchpadService/Update',
                request_serializer=antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadResponse.FromString,
                _registered_method=True)
        self.GetCost = channel.unary_unary(
                '/antd.v1.ScratchpadService/GetCost',
                request_serializer=antd_dot_v1_dot_scratchpads__pb2.ScratchpadCostRequest.SerializeToString,
                response_deserializer=antd_dot_v1_dot_common__pb2.Cost.FromString,
                _registered_method=True)


class ScratchpadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExistence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScratchpadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=antd_dot_v1_dot_scratchpads__pb2.GetScratchpadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_scratchpads__pb2.GetScratchpadResponse.SerializeToString,
            ),
            'CheckExistence': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExistence,
                    request_deserializer=antd_dot_v1_dot_scratchpads__pb2.CheckScratchpadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_scratchpads__pb2.ScratchpadExistsResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadRequest.FromString,
                    response_serializer=antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadResponse.SerializeToString,
            ),
            'GetCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCost,
                    request_deserializer=antd_dot_v1_dot_scratchpads__pb2.ScratchpadCostRequest.FromString,
                    response_serializer=antd_dot_v1_dot_common__pb2.Cost.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antd.v1.ScratchpadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antd.v1.ScratchpadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScratchpadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.ScratchpadService/Get',
            antd_dot_v1_dot_scratchpads__pb2.GetScratchpadRequest.SerializeToString,
            antd_dot_v1_dot_scratchpads__pb2.GetScratchpadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckExistence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.ScratchpadService/CheckExistence',
            antd_dot_v1_dot_scratchpads__pb2.CheckScratchpadRequest.SerializeToString,
            antd_dot_v1_dot_scratchpads__pb2.ScratchpadExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.ScratchpadService/Create',
            antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadRequest.SerializeToString,
            antd_dot_v1_dot_scratchpads__pb2.CreateScratchpadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.ScratchpadService/Update',
            antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadRequest.SerializeToString,
            antd_dot_v1_dot_scratchpads__pb2.UpdateScratchpadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antd.v1.ScratchpadService/GetCost',
            antd_dot_v1_dot_scratchpads__pb2.ScratchpadCostRequest.SerializeToString,
            antd_dot_v1_dot_common__pb2.Cost.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
