# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/scratchpads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/scratchpads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ntd/v1/scratchpads.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"\'\n\x14GetScratchpadRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"^\n\x15GetScratchpadResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x15\n\rdata_encoding\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0f\n\x07\x63ounter\x18\x04 \x01(\x04\")\n\x16\x43heckScratchpadRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"*\n\x18ScratchpadExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"W\n\x17\x43reateScratchpadRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"H\n\x18\x43reateScratchpadResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"W\n\x17UpdateScratchpadRequest\x12\x18\n\x10owner_secret_key\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x1a\n\x18UpdateScratchpadResponse\"+\n\x15ScratchpadCostRequest\x12\x12\n\npublic_key\x18\x01 \x01(\t2\x87\x03\n\x11ScratchpadService\x12\x44\n\x03Get\x12\x1d.antd.v1.GetScratchpadRequest\x1a\x1e.antd.v1.GetScratchpadResponse\x12T\n\x0e\x43heckExistence\x12\x1f.antd.v1.CheckScratchpadRequest\x1a!.antd.v1.ScratchpadExistsResponse\x12M\n\x06\x43reate\x12 .antd.v1.CreateScratchpadRequest\x1a!.antd.v1.CreateScratchpadResponse\x12M\n\x06Update\x12 .antd.v1.UpdateScratchpadRequest\x1a!.antd.v1.UpdateScratchpadResponse\x12\x38\n\x07GetCost\x12\x1e.antd.v1.ScratchpadCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.scratchpads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETSCRATCHPADREQUEST']._serialized_start=60
  _globals['_GETSCRATCHPADREQUEST']._serialized_end=99
  _globals['_GETSCRATCHPADRESPONSE']._serialized_start=101
  _globals['_GETSCRATCHPADRESPONSE']._serialized_end=195
  _globals['_CHECKSCRATCHPADREQUEST']._serialized_start=197
  _globals['_CHECKSCRATCHPADREQUEST']._serialized_end=238
  _globals['_SCRATCHPADEXISTSRESPONSE']._serialized_start=240
  _globals['_SCRATCHPADEXISTSRESPONSE']._serialized_end=282
  _globals['_CREATESCRATCHPADREQUEST']._serialized_start=284
  _globals['_CREATESCRATCHPADREQUEST']._serialized_end=371
  _globals['_CREATESCRATCHPADRESPONSE']._serialized_start=373
  _globals['_CREATESCRATCHPADRESPONSE']._serialized_end=445
  _globals['_UPDATESCRATCHPADREQUEST']._serialized_start=447
  _globals['_UPDATESCRATCHPADREQUEST']._serialized_end=534
  _globals['_UPDATESCRATCHPADRESPONSE']._serialized_start=536
  _globals['_UPDATESCRATCHPADRESPONSE']._serialized_end=562
  _globals['_SCRATCHPADCOSTREQUEST']._serialized_start=564
  _globals['_SCRATCHPADCOSTREQUEST']._serialized_end=607
  _globals['_SCRATCHPADSERVICE']._serialized_start=610
  _globals['_SCRATCHPADSERVICE']._serialized_end=1001
# @@protoc_insertion_point(module_scope)
