# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antd/v1/vaults.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antd/v1/vaults.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antd._proto.antd.v1 import common_pb2 as antd_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61ntd/v1/vaults.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"%\n\x0fGetVaultRequest\x12\x12\n\nsecret_key\x18\x01 \x01(\t\"6\n\x10GetVaultResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\x04\"I\n\x0fPutVaultRequest\x12\x12\n\nsecret_key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\x04\"/\n\x10PutVaultResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\"8\n\x10VaultCostRequest\x12\x12\n\nsecret_key\x18\x01 \x01(\t\x12\x10\n\x08max_size\x18\x02 \x01(\x04\x32\xbb\x01\n\x0cVaultService\x12:\n\x03Get\x12\x18.antd.v1.GetVaultRequest\x1a\x19.antd.v1.GetVaultResponse\x12:\n\x03Put\x12\x18.antd.v1.PutVaultRequest\x1a\x19.antd.v1.PutVaultResponse\x12\x33\n\x07GetCost\x12\x19.antd.v1.VaultCostRequest\x1a\r.antd.v1.CostB\n\xaa\x02\x07\x41ntd.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antd._proto.antd.v1.vaults_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\007Antd.V1'
  _globals['_GETVAULTREQUEST']._serialized_start=55
  _globals['_GETVAULTREQUEST']._serialized_end=92
  _globals['_GETVAULTRESPONSE']._serialized_start=94
  _globals['_GETVAULTRESPONSE']._serialized_end=148
  _globals['_PUTVAULTREQUEST']._serialized_start=150
  _globals['_PUTVAULTREQUEST']._serialized_end=223
  _globals['_PUTVAULTRESPONSE']._serialized_start=225
  _globals['_PUTVAULTRESPONSE']._serialized_end=272
  _globals['_VAULTCOSTREQUEST']._serialized_start=274
  _globals['_VAULTCOSTREQUEST']._serialized_end=330
  _globals['_VAULTSERVICE']._serialized_start=333
  _globals['_VAULTSERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
