# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/chunks.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/chunks_pb'

module Antd
  module V1
    module ChunkService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.ChunkService'

        rpc :Get, ::Antd::V1::GetChunkRequest, ::Antd::V1::GetChunkResponse
        rpc :Put, ::Antd::V1::PutChunkRequest, ::Antd::V1::PutChunkResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
