# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antd/v1/chunks.proto

require 'google/protobuf'

require 'antd/v1/common_pb'


descriptor_data = "\n\x14\x61ntd/v1/chunks.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"\"\n\x0fGetChunkRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\" \n\x10GetChunkResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1f\n\x0fPutChunkRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"@\n\x10PutChunkResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\x86\x01\n\x0c\x43hunkService\x12:\n\x03Get\x12\x18.antd.v1.GetChunkRequest\x1a\x19.antd.v1.GetChunkResponse\x12:\n\x03Put\x12\x18.antd.v1.PutChunkRequest\x1a\x19.antd.v1.PutChunkResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Antd
  module V1
    GetChunkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetChunkRequest").msgclass
    GetChunkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetChunkResponse").msgclass
    PutChunkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutChunkRequest").msgclass
    PutChunkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutChunkResponse").msgclass
  end
end
