# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/data.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/data_pb'

module Antd
  module V1
    module DataService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.DataService'

        rpc :GetPublic, ::Antd::V1::GetPublicDataRequest, ::Antd::V1::GetPublicDataResponse
        rpc :PutPublic, ::Antd::V1::PutPublicDataRequest, ::Antd::V1::PutPublicDataResponse
        rpc :StreamPublic, ::Antd::V1::StreamPublicDataRequest, stream(::Antd::V1::DataChunk)
        rpc :GetPrivate, ::Antd::V1::GetPrivateDataRequest, ::Antd::V1::GetPrivateDataResponse
        rpc :PutPrivate, ::Antd::V1::PutPrivateDataRequest, ::Antd::V1::PutPrivateDataResponse
        rpc :GetCost, ::Antd::V1::DataCostRequest, ::Antd::V1::Cost
      end

      Stub = Service.rpc_stub_class
    end
  end
end
