# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antd/v1/data.proto

require 'google/protobuf'

require 'antd/v1/common_pb'


descriptor_data = "\n\x12\x61ntd/v1/data.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"\'\n\x14GetPublicDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"%\n\x15GetPublicDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x14PutPublicDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"E\n\x15PutPublicDataResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"*\n\x17StreamPublicDataRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x19\n\tDataChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\")\n\x15GetPrivateDataRequest\x12\x10\n\x08\x64\x61ta_map\x18\x01 \x01(\t\"&\n\x16GetPrivateDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x15PutPrivateDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"G\n\x16PutPrivateDataResponse\x12\x1b\n\x04\x63ost\x18\x01 \x01(\x0b\x32\r.antd.v1.Cost\x12\x10\n\x08\x64\x61ta_map\x18\x02 \x01(\t\"\x1f\n\x0f\x44\x61taCostRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xbf\x03\n\x0b\x44\x61taService\x12J\n\tGetPublic\x12\x1d.antd.v1.GetPublicDataRequest\x1a\x1e.antd.v1.GetPublicDataResponse\x12J\n\tPutPublic\x12\x1d.antd.v1.PutPublicDataRequest\x1a\x1e.antd.v1.PutPublicDataResponse\x12\x46\n\x0cStreamPublic\x12 .antd.v1.StreamPublicDataRequest\x1a\x12.antd.v1.DataChunk0\x01\x12M\n\nGetPrivate\x12\x1e.antd.v1.GetPrivateDataRequest\x1a\x1f.antd.v1.GetPrivateDataResponse\x12M\n\nPutPrivate\x12\x1e.antd.v1.PutPrivateDataRequest\x1a\x1f.antd.v1.PutPrivateDataResponse\x12\x32\n\x07GetCost\x12\x18.antd.v1.DataCostRequest\x1a\r.antd.v1.CostBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Antd
  module V1
    GetPublicDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetPublicDataRequest").msgclass
    GetPublicDataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetPublicDataResponse").msgclass
    PutPublicDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutPublicDataRequest").msgclass
    PutPublicDataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutPublicDataResponse").msgclass
    StreamPublicDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.StreamPublicDataRequest").msgclass
    DataChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.DataChunk").msgclass
    GetPrivateDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetPrivateDataRequest").msgclass
    GetPrivateDataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.GetPrivateDataResponse").msgclass
    PutPrivateDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutPrivateDataRequest").msgclass
    PutPrivateDataResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.PutPrivateDataResponse").msgclass
    DataCostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.DataCostRequest").msgclass
  end
end
