# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antd/v1/files.proto

require 'google/protobuf'

require 'antd/v1/common_pb'


descriptor_data = "\n\x13\x61ntd/v1/files.proto\x12\x07\x61ntd.v1\x1a\x14\x61ntd/v1/common.proto\"!\n\x11UploadFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x96\x01\n\x14UploadPublicResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x19\n\x11storage_cost_atto\x18\x03 \x01(\t\x12\x14\n\x0cgas_cost_wei\x18\x04 \x01(\t\x12\x15\n\rchunks_stored\x18\x05 \x01(\x04\x12\x19\n\x11payment_mode_used\x18\x06 \x01(\tJ\x04\x08\x01\x10\x02R\x04\x63ost\";\n\x15\x44ownloadPublicRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\tdest_path\x18\x02 \x01(\t\"\x12\n\x10\x44ownloadResponse\"2\n\x0f\x46ileCostRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x32\xfb\x02\n\x0b\x46ileService\x12I\n\x0cUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12K\n\x0e\x44ownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x12L\n\x0f\x44irUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12N\n\x11\x44irDownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x12\x36\n\x0bGetFileCost\x12\x18.antd.v1.FileCostRequest\x1a\r.antd.v1.CostBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\x07\x41ntd.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Antd
  module V1
    UploadFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.UploadFileRequest").msgclass
    UploadPublicResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.UploadPublicResponse").msgclass
    DownloadPublicRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.DownloadPublicRequest").msgclass
    DownloadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.DownloadResponse").msgclass
    FileCostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("antd.v1.FileCostRequest").msgclass
  end
end
