# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: antd/v1/files.proto for package 'antd.v1'

require 'grpc'
require 'antd/v1/files_pb'

module Antd
  module V1
    module FileService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'antd.v1.FileService'

        rpc :UploadPublic, ::Antd::V1::UploadFileRequest, ::Antd::V1::UploadPublicResponse
        rpc :DownloadPublic, ::Antd::V1::DownloadPublicRequest, ::Antd::V1::DownloadResponse
        rpc :DirUploadPublic, ::Antd::V1::UploadFileRequest, ::Antd::V1::UploadPublicResponse
        rpc :DirDownloadPublic, ::Antd::V1::DownloadPublicRequest, ::Antd::V1::DownloadResponse
        rpc :GetFileCost, ::Antd::V1::FileCostRequest, ::Antd::V1::Cost
      end

      Stub = Service.rpc_stub_class
    end
  end
end
