// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: antd/v1/chunks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{0}
}

func (x *GetChunkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{1}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_antd_v1_chunks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{2}
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *Cost                  `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_antd_v1_chunks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_chunks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_chunks_proto_rawDescGZIP(), []int{3}
}

func (x *PutChunkResponse) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PutChunkResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_antd_v1_chunks_proto protoreflect.FileDescriptor

const file_antd_v1_chunks_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/chunks.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"+\n" +
	"\x0fGetChunkRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fPutChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"O\n" +
	"\x10PutChunkResponse\x12!\n" +
	"\x04cost\x18\x01 \x01(\v2\r.antd.v1.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\x86\x01\n" +
	"\fChunkService\x12:\n" +
	"\x03Get\x12\x18.antd.v1.GetChunkRequest\x1a\x19.antd.v1.GetChunkResponse\x12:\n" +
	"\x03Put\x12\x18.antd.v1.PutChunkRequest\x1a\x19.antd.v1.PutChunkResponseB\n" +
	"\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_chunks_proto_rawDescOnce sync.Once
	file_antd_v1_chunks_proto_rawDescData []byte
)

func file_antd_v1_chunks_proto_rawDescGZIP() []byte {
	file_antd_v1_chunks_proto_rawDescOnce.Do(func() {
		file_antd_v1_chunks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_chunks_proto_rawDesc), len(file_antd_v1_chunks_proto_rawDesc)))
	})
	return file_antd_v1_chunks_proto_rawDescData
}

var file_antd_v1_chunks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_antd_v1_chunks_proto_goTypes = []any{
	(*GetChunkRequest)(nil),  // 0: antd.v1.GetChunkRequest
	(*GetChunkResponse)(nil), // 1: antd.v1.GetChunkResponse
	(*PutChunkRequest)(nil),  // 2: antd.v1.PutChunkRequest
	(*PutChunkResponse)(nil), // 3: antd.v1.PutChunkResponse
	(*Cost)(nil),             // 4: antd.v1.Cost
}
var file_antd_v1_chunks_proto_depIdxs = []int32{
	4, // 0: antd.v1.PutChunkResponse.cost:type_name -> antd.v1.Cost
	0, // 1: antd.v1.ChunkService.Get:input_type -> antd.v1.GetChunkRequest
	2, // 2: antd.v1.ChunkService.Put:input_type -> antd.v1.PutChunkRequest
	1, // 3: antd.v1.ChunkService.Get:output_type -> antd.v1.GetChunkResponse
	3, // 4: antd.v1.ChunkService.Put:output_type -> antd.v1.PutChunkResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_antd_v1_chunks_proto_init() }
func file_antd_v1_chunks_proto_init() {
	if File_antd_v1_chunks_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_chunks_proto_rawDesc), len(file_antd_v1_chunks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_chunks_proto_goTypes,
		DependencyIndexes: file_antd_v1_chunks_proto_depIdxs,
		MessageInfos:      file_antd_v1_chunks_proto_msgTypes,
	}.Build()
	File_antd_v1_chunks_proto = out.File
	file_antd_v1_chunks_proto_goTypes = nil
	file_antd_v1_chunks_proto_depIdxs = nil
}
