// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: antd/v1/data.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_GetPublic_FullMethodName    = "/antd.v1.DataService/GetPublic"
	DataService_PutPublic_FullMethodName    = "/antd.v1.DataService/PutPublic"
	DataService_StreamPublic_FullMethodName = "/antd.v1.DataService/StreamPublic"
	DataService_GetPrivate_FullMethodName   = "/antd.v1.DataService/GetPrivate"
	DataService_PutPrivate_FullMethodName   = "/antd.v1.DataService/PutPrivate"
	DataService_GetCost_FullMethodName      = "/antd.v1.DataService/GetCost"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	GetPublic(ctx context.Context, in *GetPublicDataRequest, opts ...grpc.CallOption) (*GetPublicDataResponse, error)
	PutPublic(ctx context.Context, in *PutPublicDataRequest, opts ...grpc.CallOption) (*PutPublicDataResponse, error)
	StreamPublic(ctx context.Context, in *StreamPublicDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	GetPrivate(ctx context.Context, in *GetPrivateDataRequest, opts ...grpc.CallOption) (*GetPrivateDataResponse, error)
	PutPrivate(ctx context.Context, in *PutPrivateDataRequest, opts ...grpc.CallOption) (*PutPrivateDataResponse, error)
	GetCost(ctx context.Context, in *DataCostRequest, opts ...grpc.CallOption) (*Cost, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetPublic(ctx context.Context, in *GetPublicDataRequest, opts ...grpc.CallOption) (*GetPublicDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicDataResponse)
	err := c.cc.Invoke(ctx, DataService_GetPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PutPublic(ctx context.Context, in *PutPublicDataRequest, opts ...grpc.CallOption) (*PutPublicDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPublicDataResponse)
	err := c.cc.Invoke(ctx, DataService_PutPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) StreamPublic(ctx context.Context, in *StreamPublicDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_StreamPublic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPublicDataRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamPublicClient = grpc.ServerStreamingClient[DataChunk]

func (c *dataServiceClient) GetPrivate(ctx context.Context, in *GetPrivateDataRequest, opts ...grpc.CallOption) (*GetPrivateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateDataResponse)
	err := c.cc.Invoke(ctx, DataService_GetPrivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PutPrivate(ctx context.Context, in *PutPrivateDataRequest, opts ...grpc.CallOption) (*PutPrivateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPrivateDataResponse)
	err := c.cc.Invoke(ctx, DataService_PutPrivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetCost(ctx context.Context, in *DataCostRequest, opts ...grpc.CallOption) (*Cost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cost)
	err := c.cc.Invoke(ctx, DataService_GetCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	GetPublic(context.Context, *GetPublicDataRequest) (*GetPublicDataResponse, error)
	PutPublic(context.Context, *PutPublicDataRequest) (*PutPublicDataResponse, error)
	StreamPublic(*StreamPublicDataRequest, grpc.ServerStreamingServer[DataChunk]) error
	GetPrivate(context.Context, *GetPrivateDataRequest) (*GetPrivateDataResponse, error)
	PutPrivate(context.Context, *PutPrivateDataRequest) (*PutPrivateDataResponse, error)
	GetCost(context.Context, *DataCostRequest) (*Cost, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) GetPublic(context.Context, *GetPublicDataRequest) (*GetPublicDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublic not implemented")
}
func (UnimplementedDataServiceServer) PutPublic(context.Context, *PutPublicDataRequest) (*PutPublicDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPublic not implemented")
}
func (UnimplementedDataServiceServer) StreamPublic(*StreamPublicDataRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamPublic not implemented")
}
func (UnimplementedDataServiceServer) GetPrivate(context.Context, *GetPrivateDataRequest) (*GetPrivateDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivate not implemented")
}
func (UnimplementedDataServiceServer) PutPrivate(context.Context, *PutPrivateDataRequest) (*PutPrivateDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPrivate not implemented")
}
func (UnimplementedDataServiceServer) GetCost(context.Context, *DataCostRequest) (*Cost, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCost not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_GetPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetPublic(ctx, req.(*GetPublicDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PutPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPublicDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PutPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_PutPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PutPublic(ctx, req.(*PutPublicDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_StreamPublic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPublicDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).StreamPublic(m, &grpc.GenericServerStream[StreamPublicDataRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_StreamPublicServer = grpc.ServerStreamingServer[DataChunk]

func _DataService_GetPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetPrivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetPrivate(ctx, req.(*GetPrivateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PutPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPrivateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PutPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_PutPrivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PutPrivate(ctx, req.(*PutPrivateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetCost(ctx, req.(*DataCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublic",
			Handler:    _DataService_GetPublic_Handler,
		},
		{
			MethodName: "PutPublic",
			Handler:    _DataService_PutPublic_Handler,
		},
		{
			MethodName: "GetPrivate",
			Handler:    _DataService_GetPrivate_Handler,
		},
		{
			MethodName: "PutPrivate",
			Handler:    _DataService_PutPrivate_Handler,
		},
		{
			MethodName: "GetCost",
			Handler:    _DataService_GetCost_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPublic",
			Handler:       _DataService_StreamPublic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "antd/v1/data.proto",
}
