// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: antd/v1/data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicDataRequest) Reset() {
	*x = GetPublicDataRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicDataRequest) ProtoMessage() {}

func (x *GetPublicDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicDataRequest.ProtoReflect.Descriptor instead.
func (*GetPublicDataRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicDataRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPublicDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicDataResponse) Reset() {
	*x = GetPublicDataResponse{}
	mi := &file_antd_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicDataResponse) ProtoMessage() {}

func (x *GetPublicDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicDataResponse.ProtoReflect.Descriptor instead.
func (*GetPublicDataResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutPublicDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional payment mode: "auto" (default), "merkle", or "single". Empty
	// string is treated as "auto" so old clients omitting the field stay
	// wire-compatible.
	PaymentMode   string `protobuf:"bytes,2,opt,name=payment_mode,json=paymentMode,proto3" json:"payment_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPublicDataRequest) Reset() {
	*x = PutPublicDataRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPublicDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPublicDataRequest) ProtoMessage() {}

func (x *PutPublicDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPublicDataRequest.ProtoReflect.Descriptor instead.
func (*PutPublicDataRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *PutPublicDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutPublicDataRequest) GetPaymentMode() string {
	if x != nil {
		return x.PaymentMode
	}
	return ""
}

type PutPublicDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *Cost                  `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPublicDataResponse) Reset() {
	*x = PutPublicDataResponse{}
	mi := &file_antd_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPublicDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPublicDataResponse) ProtoMessage() {}

func (x *PutPublicDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPublicDataResponse.ProtoReflect.Descriptor instead.
func (*PutPublicDataResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *PutPublicDataResponse) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PutPublicDataResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type StreamPublicDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPublicDataRequest) Reset() {
	*x = StreamPublicDataRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPublicDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPublicDataRequest) ProtoMessage() {}

func (x *StreamPublicDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPublicDataRequest.ProtoReflect.Descriptor instead.
func (*StreamPublicDataRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *StreamPublicDataRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_antd_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataMap       string                 `protobuf:"bytes,1,opt,name=data_map,json=dataMap,proto3" json:"data_map,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *GetDataRequest) GetDataMap() string {
	if x != nil {
		return x.DataMap
	}
	return ""
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_antd_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *GetDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional payment mode: "auto" (default), "merkle", or "single". Empty
	// string is treated as "auto" so old clients omitting the field stay
	// wire-compatible.
	PaymentMode   string `protobuf:"bytes,2,opt,name=payment_mode,json=paymentMode,proto3" json:"payment_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataRequest) Reset() {
	*x = PutDataRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataRequest) ProtoMessage() {}

func (x *PutDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataRequest.ProtoReflect.Descriptor instead.
func (*PutDataRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *PutDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutDataRequest) GetPaymentMode() string {
	if x != nil {
		return x.PaymentMode
	}
	return ""
}

type PutDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *Cost                  `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	DataMap       string                 `protobuf:"bytes,2,opt,name=data_map,json=dataMap,proto3" json:"data_map,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataResponse) Reset() {
	*x = PutDataResponse{}
	mi := &file_antd_v1_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataResponse) ProtoMessage() {}

func (x *PutDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataResponse.ProtoReflect.Descriptor instead.
func (*PutDataResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{9}
}

func (x *PutDataResponse) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PutDataResponse) GetDataMap() string {
	if x != nil {
		return x.DataMap
	}
	return ""
}

type DataCostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional payment mode the estimate should reflect: "auto" (default),
	// "merkle", or "single". Empty string is treated as "auto".
	PaymentMode   string `protobuf:"bytes,2,opt,name=payment_mode,json=paymentMode,proto3" json:"payment_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCostRequest) Reset() {
	*x = DataCostRequest{}
	mi := &file_antd_v1_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCostRequest) ProtoMessage() {}

func (x *DataCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCostRequest.ProtoReflect.Descriptor instead.
func (*DataCostRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_data_proto_rawDescGZIP(), []int{10}
}

func (x *DataCostRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataCostRequest) GetPaymentMode() string {
	if x != nil {
		return x.PaymentMode
	}
	return ""
}

var File_antd_v1_data_proto protoreflect.FileDescriptor

const file_antd_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x12antd/v1/data.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"0\n" +
	"\x14GetPublicDataRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"+\n" +
	"\x15GetPublicDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"M\n" +
	"\x14PutPublicDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fpayment_mode\x18\x02 \x01(\tR\vpaymentMode\"T\n" +
	"\x15PutPublicDataResponse\x12!\n" +
	"\x04cost\x18\x01 \x01(\v2\r.antd.v1.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"3\n" +
	"\x17StreamPublicDataRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x1f\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"+\n" +
	"\x0eGetDataRequest\x12\x19\n" +
	"\bdata_map\x18\x01 \x01(\tR\adataMap\"%\n" +
	"\x0fGetDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"G\n" +
	"\x0ePutDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fpayment_mode\x18\x02 \x01(\tR\vpaymentMode\"O\n" +
	"\x0fPutDataResponse\x12!\n" +
	"\x04cost\x18\x01 \x01(\v2\r.antd.v1.CostR\x04cost\x12\x19\n" +
	"\bdata_map\x18\x02 \x01(\tR\adataMap\"H\n" +
	"\x0fDataCostRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fpayment_mode\x18\x02 \x01(\tR\vpaymentMode2\x92\x03\n" +
	"\vDataService\x128\n" +
	"\x03Put\x12\x17.antd.v1.PutDataRequest\x1a\x18.antd.v1.PutDataResponse\x12J\n" +
	"\tPutPublic\x12\x1d.antd.v1.PutPublicDataRequest\x1a\x1e.antd.v1.PutPublicDataResponse\x128\n" +
	"\x03Get\x12\x17.antd.v1.GetDataRequest\x1a\x18.antd.v1.GetDataResponse\x12J\n" +
	"\tGetPublic\x12\x1d.antd.v1.GetPublicDataRequest\x1a\x1e.antd.v1.GetPublicDataResponse\x12F\n" +
	"\fStreamPublic\x12 .antd.v1.StreamPublicDataRequest\x1a\x12.antd.v1.DataChunk0\x01\x12/\n" +
	"\x04Cost\x12\x18.antd.v1.DataCostRequest\x1a\r.antd.v1.CostBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_data_proto_rawDescOnce sync.Once
	file_antd_v1_data_proto_rawDescData []byte
)

func file_antd_v1_data_proto_rawDescGZIP() []byte {
	file_antd_v1_data_proto_rawDescOnce.Do(func() {
		file_antd_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_data_proto_rawDesc), len(file_antd_v1_data_proto_rawDesc)))
	})
	return file_antd_v1_data_proto_rawDescData
}

var file_antd_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_antd_v1_data_proto_goTypes = []any{
	(*GetPublicDataRequest)(nil),    // 0: antd.v1.GetPublicDataRequest
	(*GetPublicDataResponse)(nil),   // 1: antd.v1.GetPublicDataResponse
	(*PutPublicDataRequest)(nil),    // 2: antd.v1.PutPublicDataRequest
	(*PutPublicDataResponse)(nil),   // 3: antd.v1.PutPublicDataResponse
	(*StreamPublicDataRequest)(nil), // 4: antd.v1.StreamPublicDataRequest
	(*DataChunk)(nil),               // 5: antd.v1.DataChunk
	(*GetDataRequest)(nil),          // 6: antd.v1.GetDataRequest
	(*GetDataResponse)(nil),         // 7: antd.v1.GetDataResponse
	(*PutDataRequest)(nil),          // 8: antd.v1.PutDataRequest
	(*PutDataResponse)(nil),         // 9: antd.v1.PutDataResponse
	(*DataCostRequest)(nil),         // 10: antd.v1.DataCostRequest
	(*Cost)(nil),                    // 11: antd.v1.Cost
}
var file_antd_v1_data_proto_depIdxs = []int32{
	11, // 0: antd.v1.PutPublicDataResponse.cost:type_name -> antd.v1.Cost
	11, // 1: antd.v1.PutDataResponse.cost:type_name -> antd.v1.Cost
	8,  // 2: antd.v1.DataService.Put:input_type -> antd.v1.PutDataRequest
	2,  // 3: antd.v1.DataService.PutPublic:input_type -> antd.v1.PutPublicDataRequest
	6,  // 4: antd.v1.DataService.Get:input_type -> antd.v1.GetDataRequest
	0,  // 5: antd.v1.DataService.GetPublic:input_type -> antd.v1.GetPublicDataRequest
	4,  // 6: antd.v1.DataService.StreamPublic:input_type -> antd.v1.StreamPublicDataRequest
	10, // 7: antd.v1.DataService.Cost:input_type -> antd.v1.DataCostRequest
	9,  // 8: antd.v1.DataService.Put:output_type -> antd.v1.PutDataResponse
	3,  // 9: antd.v1.DataService.PutPublic:output_type -> antd.v1.PutPublicDataResponse
	7,  // 10: antd.v1.DataService.Get:output_type -> antd.v1.GetDataResponse
	1,  // 11: antd.v1.DataService.GetPublic:output_type -> antd.v1.GetPublicDataResponse
	5,  // 12: antd.v1.DataService.StreamPublic:output_type -> antd.v1.DataChunk
	11, // 13: antd.v1.DataService.Cost:output_type -> antd.v1.Cost
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_antd_v1_data_proto_init() }
func file_antd_v1_data_proto_init() {
	if File_antd_v1_data_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_data_proto_rawDesc), len(file_antd_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_data_proto_goTypes,
		DependencyIndexes: file_antd_v1_data_proto_depIdxs,
		MessageInfos:      file_antd_v1_data_proto_msgTypes,
	}.Build()
	File_antd_v1_data_proto = out.File
	file_antd_v1_data_proto_goTypes = nil
	file_antd_v1_data_proto_depIdxs = nil
}
