// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: antd/v1/files.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // local filesystem path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_antd_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UploadPublicResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex
	// Total storage cost paid in token units (atto). "0" if all chunks already existed.
	StorageCostAtto string `protobuf:"bytes,3,opt,name=storage_cost_atto,json=storageCostAtto,proto3" json:"storage_cost_atto,omitempty"`
	// Total gas cost paid in wei, as a decimal string (u128 exceeds JSON safe-integer range).
	GasCostWei string `protobuf:"bytes,4,opt,name=gas_cost_wei,json=gasCostWei,proto3" json:"gas_cost_wei,omitempty"`
	// Number of chunks stored on the network.
	ChunksStored uint64 `protobuf:"varint,5,opt,name=chunks_stored,json=chunksStored,proto3" json:"chunks_stored,omitempty"`
	// Which payment mode was actually used ("auto", "merkle", or "single").
	PaymentModeUsed string `protobuf:"bytes,6,opt,name=payment_mode_used,json=paymentModeUsed,proto3" json:"payment_mode_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadPublicResponse) Reset() {
	*x = UploadPublicResponse{}
	mi := &file_antd_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPublicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPublicResponse) ProtoMessage() {}

func (x *UploadPublicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPublicResponse.ProtoReflect.Descriptor instead.
func (*UploadPublicResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *UploadPublicResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UploadPublicResponse) GetStorageCostAtto() string {
	if x != nil {
		return x.StorageCostAtto
	}
	return ""
}

func (x *UploadPublicResponse) GetGasCostWei() string {
	if x != nil {
		return x.GasCostWei
	}
	return ""
}

func (x *UploadPublicResponse) GetChunksStored() uint64 {
	if x != nil {
		return x.ChunksStored
	}
	return 0
}

func (x *UploadPublicResponse) GetPaymentModeUsed() string {
	if x != nil {
		return x.PaymentModeUsed
	}
	return ""
}

type DownloadPublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                   // hex
	DestPath      string                 `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"` // local filesystem path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPublicRequest) Reset() {
	*x = DownloadPublicRequest{}
	mi := &file_antd_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPublicRequest) ProtoMessage() {}

func (x *DownloadPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPublicRequest.ProtoReflect.Descriptor instead.
func (*DownloadPublicRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadPublicRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DownloadPublicRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_antd_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_files_proto_rawDescGZIP(), []int{3}
}

type FileCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCostRequest) Reset() {
	*x = FileCostRequest{}
	mi := &file_antd_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCostRequest) ProtoMessage() {}

func (x *FileCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCostRequest.ProtoReflect.Descriptor instead.
func (*FileCostRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *FileCostRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileCostRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

var File_antd_v1_files_proto protoreflect.FileDescriptor

const file_antd_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x13antd/v1/files.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"'\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xdb\x01\n" +
	"\x14UploadPublicResponse\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12*\n" +
	"\x11storage_cost_atto\x18\x03 \x01(\tR\x0fstorageCostAtto\x12 \n" +
	"\fgas_cost_wei\x18\x04 \x01(\tR\n" +
	"gasCostWei\x12#\n" +
	"\rchunks_stored\x18\x05 \x01(\x04R\fchunksStored\x12*\n" +
	"\x11payment_mode_used\x18\x06 \x01(\tR\x0fpaymentModeUsedJ\x04\b\x01\x10\x02R\x04cost\"N\n" +
	"\x15DownloadPublicRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\"\x12\n" +
	"\x10DownloadResponse\"B\n" +
	"\x0fFileCostRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic2\xfb\x02\n" +
	"\vFileService\x12I\n" +
	"\fUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12K\n" +
	"\x0eDownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x12L\n" +
	"\x0fDirUploadPublic\x12\x1a.antd.v1.UploadFileRequest\x1a\x1d.antd.v1.UploadPublicResponse\x12N\n" +
	"\x11DirDownloadPublic\x12\x1e.antd.v1.DownloadPublicRequest\x1a\x19.antd.v1.DownloadResponse\x126\n" +
	"\vGetFileCost\x12\x18.antd.v1.FileCostRequest\x1a\r.antd.v1.CostBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_files_proto_rawDescOnce sync.Once
	file_antd_v1_files_proto_rawDescData []byte
)

func file_antd_v1_files_proto_rawDescGZIP() []byte {
	file_antd_v1_files_proto_rawDescOnce.Do(func() {
		file_antd_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_files_proto_rawDesc), len(file_antd_v1_files_proto_rawDesc)))
	})
	return file_antd_v1_files_proto_rawDescData
}

var file_antd_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_antd_v1_files_proto_goTypes = []any{
	(*UploadFileRequest)(nil),     // 0: antd.v1.UploadFileRequest
	(*UploadPublicResponse)(nil),  // 1: antd.v1.UploadPublicResponse
	(*DownloadPublicRequest)(nil), // 2: antd.v1.DownloadPublicRequest
	(*DownloadResponse)(nil),      // 3: antd.v1.DownloadResponse
	(*FileCostRequest)(nil),       // 4: antd.v1.FileCostRequest
	(*Cost)(nil),                  // 5: antd.v1.Cost
}
var file_antd_v1_files_proto_depIdxs = []int32{
	0, // 0: antd.v1.FileService.UploadPublic:input_type -> antd.v1.UploadFileRequest
	2, // 1: antd.v1.FileService.DownloadPublic:input_type -> antd.v1.DownloadPublicRequest
	0, // 2: antd.v1.FileService.DirUploadPublic:input_type -> antd.v1.UploadFileRequest
	2, // 3: antd.v1.FileService.DirDownloadPublic:input_type -> antd.v1.DownloadPublicRequest
	4, // 4: antd.v1.FileService.GetFileCost:input_type -> antd.v1.FileCostRequest
	1, // 5: antd.v1.FileService.UploadPublic:output_type -> antd.v1.UploadPublicResponse
	3, // 6: antd.v1.FileService.DownloadPublic:output_type -> antd.v1.DownloadResponse
	1, // 7: antd.v1.FileService.DirUploadPublic:output_type -> antd.v1.UploadPublicResponse
	3, // 8: antd.v1.FileService.DirDownloadPublic:output_type -> antd.v1.DownloadResponse
	5, // 9: antd.v1.FileService.GetFileCost:output_type -> antd.v1.Cost
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antd_v1_files_proto_init() }
func file_antd_v1_files_proto_init() {
	if File_antd_v1_files_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_files_proto_rawDesc), len(file_antd_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_files_proto_goTypes,
		DependencyIndexes: file_antd_v1_files_proto_depIdxs,
		MessageInfos:      file_antd_v1_files_proto_msgTypes,
	}.Build()
	File_antd_v1_files_proto = out.File
	file_antd_v1_files_proto_goTypes = nil
	file_antd_v1_files_proto_depIdxs = nil
}
