// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: antd/v1/files.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_UploadPublic_FullMethodName      = "/antd.v1.FileService/UploadPublic"
	FileService_DownloadPublic_FullMethodName    = "/antd.v1.FileService/DownloadPublic"
	FileService_DirUploadPublic_FullMethodName   = "/antd.v1.FileService/DirUploadPublic"
	FileService_DirDownloadPublic_FullMethodName = "/antd.v1.FileService/DirDownloadPublic"
	FileService_GetFileCost_FullMethodName       = "/antd.v1.FileService/GetFileCost"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	UploadPublic(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadPublicResponse, error)
	DownloadPublic(ctx context.Context, in *DownloadPublicRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	DirUploadPublic(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadPublicResponse, error)
	DirDownloadPublic(ctx context.Context, in *DownloadPublicRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	GetFileCost(ctx context.Context, in *FileCostRequest, opts ...grpc.CallOption) (*Cost, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) UploadPublic(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadPublicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPublicResponse)
	err := c.cc.Invoke(ctx, FileService_UploadPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DownloadPublic(ctx context.Context, in *DownloadPublicRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, FileService_DownloadPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DirUploadPublic(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadPublicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPublicResponse)
	err := c.cc.Invoke(ctx, FileService_DirUploadPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DirDownloadPublic(ctx context.Context, in *DownloadPublicRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, FileService_DirDownloadPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileCost(ctx context.Context, in *FileCostRequest, opts ...grpc.CallOption) (*Cost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cost)
	err := c.cc.Invoke(ctx, FileService_GetFileCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	UploadPublic(context.Context, *UploadFileRequest) (*UploadPublicResponse, error)
	DownloadPublic(context.Context, *DownloadPublicRequest) (*DownloadResponse, error)
	DirUploadPublic(context.Context, *UploadFileRequest) (*UploadPublicResponse, error)
	DirDownloadPublic(context.Context, *DownloadPublicRequest) (*DownloadResponse, error)
	GetFileCost(context.Context, *FileCostRequest) (*Cost, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) UploadPublic(context.Context, *UploadFileRequest) (*UploadPublicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPublic not implemented")
}
func (UnimplementedFileServiceServer) DownloadPublic(context.Context, *DownloadPublicRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadPublic not implemented")
}
func (UnimplementedFileServiceServer) DirUploadPublic(context.Context, *UploadFileRequest) (*UploadPublicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirUploadPublic not implemented")
}
func (UnimplementedFileServiceServer) DirDownloadPublic(context.Context, *DownloadPublicRequest) (*DownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirDownloadPublic not implemented")
}
func (UnimplementedFileServiceServer) GetFileCost(context.Context, *FileCostRequest) (*Cost, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileCost not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_UploadPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadPublic(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DownloadPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DownloadPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DownloadPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DownloadPublic(ctx, req.(*DownloadPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DirUploadPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DirUploadPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DirUploadPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DirUploadPublic(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DirDownloadPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadPublicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DirDownloadPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DirDownloadPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DirDownloadPublic(ctx, req.(*DownloadPublicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileCost(ctx, req.(*FileCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadPublic",
			Handler:    _FileService_UploadPublic_Handler,
		},
		{
			MethodName: "DownloadPublic",
			Handler:    _FileService_DownloadPublic_Handler,
		},
		{
			MethodName: "DirUploadPublic",
			Handler:    _FileService_DirUploadPublic_Handler,
		},
		{
			MethodName: "DirDownloadPublic",
			Handler:    _FileService_DirDownloadPublic_Handler,
		},
		{
			MethodName: "GetFileCost",
			Handler:    _FileService_GetFileCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antd/v1/files.proto",
}
