// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: antd/v1/graph.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGraphEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphEntryRequest) Reset() {
	*x = GetGraphEntryRequest{}
	mi := &file_antd_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphEntryRequest) ProtoMessage() {}

func (x *GetGraphEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphEntryRequest.ProtoReflect.Descriptor instead.
func (*GetGraphEntryRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GetGraphEntryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetGraphEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Parents       []string               `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // hex, 32 bytes
	Descendants   []*GraphDescendant     `protobuf:"bytes,4,rep,name=descendants,proto3" json:"descendants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphEntryResponse) Reset() {
	*x = GetGraphEntryResponse{}
	mi := &file_antd_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphEntryResponse) ProtoMessage() {}

func (x *GetGraphEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphEntryResponse.ProtoReflect.Descriptor instead.
func (*GetGraphEntryResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GetGraphEntryResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetGraphEntryResponse) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *GetGraphEntryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetGraphEntryResponse) GetDescendants() []*GraphDescendant {
	if x != nil {
		return x.Descendants
	}
	return nil
}

type CheckGraphEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGraphEntryRequest) Reset() {
	*x = CheckGraphEntryRequest{}
	mi := &file_antd_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGraphEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGraphEntryRequest) ProtoMessage() {}

func (x *CheckGraphEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGraphEntryRequest.ProtoReflect.Descriptor instead.
func (*CheckGraphEntryRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *CheckGraphEntryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GraphExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphExistsResponse) Reset() {
	*x = GraphExistsResponse{}
	mi := &file_antd_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphExistsResponse) ProtoMessage() {}

func (x *GraphExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphExistsResponse.ProtoReflect.Descriptor instead.
func (*GraphExistsResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GraphExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PutGraphEntryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerSecretKey string                 `protobuf:"bytes,1,opt,name=owner_secret_key,json=ownerSecretKey,proto3" json:"owner_secret_key,omitempty"` // hex
	Parents        []string               `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`                                       // hex public keys
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                       // hex, 32 bytes
	Descendants    []*GraphDescendant     `protobuf:"bytes,4,rep,name=descendants,proto3" json:"descendants,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutGraphEntryRequest) Reset() {
	*x = PutGraphEntryRequest{}
	mi := &file_antd_v1_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutGraphEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutGraphEntryRequest) ProtoMessage() {}

func (x *PutGraphEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutGraphEntryRequest.ProtoReflect.Descriptor instead.
func (*PutGraphEntryRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{4}
}

func (x *PutGraphEntryRequest) GetOwnerSecretKey() string {
	if x != nil {
		return x.OwnerSecretKey
	}
	return ""
}

func (x *PutGraphEntryRequest) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *PutGraphEntryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PutGraphEntryRequest) GetDescendants() []*GraphDescendant {
	if x != nil {
		return x.Descendants
	}
	return nil
}

type PutGraphEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *Cost                  `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutGraphEntryResponse) Reset() {
	*x = PutGraphEntryResponse{}
	mi := &file_antd_v1_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutGraphEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutGraphEntryResponse) ProtoMessage() {}

func (x *PutGraphEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutGraphEntryResponse.ProtoReflect.Descriptor instead.
func (*PutGraphEntryResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{5}
}

func (x *PutGraphEntryResponse) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PutGraphEntryResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GraphEntryCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEntryCostRequest) Reset() {
	*x = GraphEntryCostRequest{}
	mi := &file_antd_v1_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEntryCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEntryCostRequest) ProtoMessage() {}

func (x *GraphEntryCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEntryCostRequest.ProtoReflect.Descriptor instead.
func (*GraphEntryCostRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_graph_proto_rawDescGZIP(), []int{6}
}

func (x *GraphEntryCostRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_antd_v1_graph_proto protoreflect.FileDescriptor

const file_antd_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x13antd/v1/graph.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"0\n" +
	"\x14GetGraphEntryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x9d\x01\n" +
	"\x15GetGraphEntryResponse\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\aparents\x18\x02 \x03(\tR\aparents\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12:\n" +
	"\vdescendants\x18\x04 \x03(\v2\x18.antd.v1.GraphDescendantR\vdescendants\"2\n" +
	"\x16CheckGraphEntryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x13GraphExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xb0\x01\n" +
	"\x14PutGraphEntryRequest\x12(\n" +
	"\x10owner_secret_key\x18\x01 \x01(\tR\x0eownerSecretKey\x12\x18\n" +
	"\aparents\x18\x02 \x03(\tR\aparents\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12:\n" +
	"\vdescendants\x18\x04 \x03(\v2\x18.antd.v1.GraphDescendantR\vdescendants\"T\n" +
	"\x15PutGraphEntryResponse\x12!\n" +
	"\x04cost\x18\x01 \x01(\v2\r.antd.v1.CostR\x04cost\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"6\n" +
	"\x15GraphEntryCostRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey2\xa5\x02\n" +
	"\fGraphService\x12D\n" +
	"\x03Get\x12\x1d.antd.v1.GetGraphEntryRequest\x1a\x1e.antd.v1.GetGraphEntryResponse\x12O\n" +
	"\x0eCheckExistence\x12\x1f.antd.v1.CheckGraphEntryRequest\x1a\x1c.antd.v1.GraphExistsResponse\x12D\n" +
	"\x03Put\x12\x1d.antd.v1.PutGraphEntryRequest\x1a\x1e.antd.v1.PutGraphEntryResponse\x128\n" +
	"\aGetCost\x12\x1e.antd.v1.GraphEntryCostRequest\x1a\r.antd.v1.CostB\n" +
	"\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_graph_proto_rawDescOnce sync.Once
	file_antd_v1_graph_proto_rawDescData []byte
)

func file_antd_v1_graph_proto_rawDescGZIP() []byte {
	file_antd_v1_graph_proto_rawDescOnce.Do(func() {
		file_antd_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_graph_proto_rawDesc), len(file_antd_v1_graph_proto_rawDesc)))
	})
	return file_antd_v1_graph_proto_rawDescData
}

var file_antd_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_antd_v1_graph_proto_goTypes = []any{
	(*GetGraphEntryRequest)(nil),   // 0: antd.v1.GetGraphEntryRequest
	(*GetGraphEntryResponse)(nil),  // 1: antd.v1.GetGraphEntryResponse
	(*CheckGraphEntryRequest)(nil), // 2: antd.v1.CheckGraphEntryRequest
	(*GraphExistsResponse)(nil),    // 3: antd.v1.GraphExistsResponse
	(*PutGraphEntryRequest)(nil),   // 4: antd.v1.PutGraphEntryRequest
	(*PutGraphEntryResponse)(nil),  // 5: antd.v1.PutGraphEntryResponse
	(*GraphEntryCostRequest)(nil),  // 6: antd.v1.GraphEntryCostRequest
	(*GraphDescendant)(nil),        // 7: antd.v1.GraphDescendant
	(*Cost)(nil),                   // 8: antd.v1.Cost
}
var file_antd_v1_graph_proto_depIdxs = []int32{
	7, // 0: antd.v1.GetGraphEntryResponse.descendants:type_name -> antd.v1.GraphDescendant
	7, // 1: antd.v1.PutGraphEntryRequest.descendants:type_name -> antd.v1.GraphDescendant
	8, // 2: antd.v1.PutGraphEntryResponse.cost:type_name -> antd.v1.Cost
	0, // 3: antd.v1.GraphService.Get:input_type -> antd.v1.GetGraphEntryRequest
	2, // 4: antd.v1.GraphService.CheckExistence:input_type -> antd.v1.CheckGraphEntryRequest
	4, // 5: antd.v1.GraphService.Put:input_type -> antd.v1.PutGraphEntryRequest
	6, // 6: antd.v1.GraphService.GetCost:input_type -> antd.v1.GraphEntryCostRequest
	1, // 7: antd.v1.GraphService.Get:output_type -> antd.v1.GetGraphEntryResponse
	3, // 8: antd.v1.GraphService.CheckExistence:output_type -> antd.v1.GraphExistsResponse
	5, // 9: antd.v1.GraphService.Put:output_type -> antd.v1.PutGraphEntryResponse
	8, // 10: antd.v1.GraphService.GetCost:output_type -> antd.v1.Cost
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_antd_v1_graph_proto_init() }
func file_antd_v1_graph_proto_init() {
	if File_antd_v1_graph_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_graph_proto_rawDesc), len(file_antd_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_graph_proto_goTypes,
		DependencyIndexes: file_antd_v1_graph_proto_depIdxs,
		MessageInfos:      file_antd_v1_graph_proto_msgTypes,
	}.Build()
	File_antd_v1_graph_proto = out.File
	file_antd_v1_graph_proto_goTypes = nil
	file_antd_v1_graph_proto_depIdxs = nil
}
