// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: antd/v1/graph.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_Get_FullMethodName            = "/antd.v1.GraphService/Get"
	GraphService_CheckExistence_FullMethodName = "/antd.v1.GraphService/CheckExistence"
	GraphService_Put_FullMethodName            = "/antd.v1.GraphService/Put"
	GraphService_GetCost_FullMethodName        = "/antd.v1.GraphService/GetCost"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphServiceClient interface {
	Get(ctx context.Context, in *GetGraphEntryRequest, opts ...grpc.CallOption) (*GetGraphEntryResponse, error)
	CheckExistence(ctx context.Context, in *CheckGraphEntryRequest, opts ...grpc.CallOption) (*GraphExistsResponse, error)
	Put(ctx context.Context, in *PutGraphEntryRequest, opts ...grpc.CallOption) (*PutGraphEntryResponse, error)
	GetCost(ctx context.Context, in *GraphEntryCostRequest, opts ...grpc.CallOption) (*Cost, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) Get(ctx context.Context, in *GetGraphEntryRequest, opts ...grpc.CallOption) (*GetGraphEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGraphEntryResponse)
	err := c.cc.Invoke(ctx, GraphService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CheckExistence(ctx context.Context, in *CheckGraphEntryRequest, opts ...grpc.CallOption) (*GraphExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphExistsResponse)
	err := c.cc.Invoke(ctx, GraphService_CheckExistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) Put(ctx context.Context, in *PutGraphEntryRequest, opts ...grpc.CallOption) (*PutGraphEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutGraphEntryResponse)
	err := c.cc.Invoke(ctx, GraphService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetCost(ctx context.Context, in *GraphEntryCostRequest, opts ...grpc.CallOption) (*Cost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cost)
	err := c.cc.Invoke(ctx, GraphService_GetCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
type GraphServiceServer interface {
	Get(context.Context, *GetGraphEntryRequest) (*GetGraphEntryResponse, error)
	CheckExistence(context.Context, *CheckGraphEntryRequest) (*GraphExistsResponse, error)
	Put(context.Context, *PutGraphEntryRequest) (*PutGraphEntryResponse, error)
	GetCost(context.Context, *GraphEntryCostRequest) (*Cost, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) Get(context.Context, *GetGraphEntryRequest) (*GetGraphEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGraphServiceServer) CheckExistence(context.Context, *CheckGraphEntryRequest) (*GraphExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExistence not implemented")
}
func (UnimplementedGraphServiceServer) Put(context.Context, *PutGraphEntryRequest) (*PutGraphEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedGraphServiceServer) GetCost(context.Context, *GraphEntryCostRequest) (*Cost, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCost not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGraphEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Get(ctx, req.(*GetGraphEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CheckExistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckGraphEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CheckExistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CheckExistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CheckExistence(ctx, req.(*CheckGraphEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutGraphEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Put(ctx, req.(*PutGraphEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphEntryCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetCost(ctx, req.(*GraphEntryCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GraphService_Get_Handler,
		},
		{
			MethodName: "CheckExistence",
			Handler:    _GraphService_CheckExistence_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _GraphService_Put_Handler,
		},
		{
			MethodName: "GetCost",
			Handler:    _GraphService_GetCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antd/v1/graph.proto",
}
