// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: antd/v1/upload.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareFileUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local filesystem path on the daemon host.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Upload visibility: "private" (default — DataMap returned to the caller)
	// or "public" (DataMap chunk bundled into the same payment batch and
	// stored on-network; its address is returned on finalize). Empty string
	// is treated as "private".
	Visibility    string `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareFileUploadRequest) Reset() {
	*x = PrepareFileUploadRequest{}
	mi := &file_antd_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareFileUploadRequest) ProtoMessage() {}

func (x *PrepareFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareFileUploadRequest.ProtoReflect.Descriptor instead.
func (*PrepareFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareFileUploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PrepareFileUploadRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type PrepareDataUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bytes to upload.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Same semantics as PrepareFileUploadRequest.visibility.
	Visibility    string `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDataUploadRequest) Reset() {
	*x = PrepareDataUploadRequest{}
	mi := &file_antd_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDataUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDataUploadRequest) ProtoMessage() {}

func (x *PrepareDataUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDataUploadRequest.ProtoReflect.Descriptor instead.
func (*PrepareDataUploadRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareDataUploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PrepareDataUploadRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type PrepareUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque token to pass back to FinalizeUpload.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// "wave_batch" or "merkle" — determines which fields are populated and
	// which contract call the external signer must make.
	PaymentType string `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	// --- Wave-batch fields (populated when payment_type == "wave_batch") ---
	// Per-quote payment entries for `payForQuotes()`.
	Payments []*PaymentEntry `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	// --- Merkle fields (populated when payment_type == "merkle") ---
	// Merkle tree depth (1..=8).
	Depth uint32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	// Pool commitments for `payForMerkleTree2()`.
	PoolCommitments []*PoolCommitmentEntry `protobuf:"bytes,5,rep,name=pool_commitments,json=poolCommitments,proto3" json:"pool_commitments,omitempty"`
	// Timestamp for the merkle payment (unix seconds).
	MerklePaymentTimestamp uint64 `protobuf:"varint,6,opt,name=merkle_payment_timestamp,json=merklePaymentTimestamp,proto3" json:"merkle_payment_timestamp,omitempty"`
	// --- Common fields (always populated) ---
	// Total amount to pay in atto tokens as a decimal string. For merkle this
	// is "0" since the cost is determined on-chain.
	TotalAmount string `protobuf:"bytes,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Unified payment vault contract address (hex with 0x prefix).
	PaymentVaultAddress string `protobuf:"bytes,8,opt,name=payment_vault_address,json=paymentVaultAddress,proto3" json:"payment_vault_address,omitempty"`
	// Payment token contract address (hex with 0x prefix).
	PaymentTokenAddress string `protobuf:"bytes,9,opt,name=payment_token_address,json=paymentTokenAddress,proto3" json:"payment_token_address,omitempty"`
	// EVM RPC URL for submitting transactions.
	RpcUrl        string `protobuf:"bytes,10,opt,name=rpc_url,json=rpcUrl,proto3" json:"rpc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareUploadResponse) Reset() {
	*x = PrepareUploadResponse{}
	mi := &file_antd_v1_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareUploadResponse) ProtoMessage() {}

func (x *PrepareUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareUploadResponse.ProtoReflect.Descriptor instead.
func (*PrepareUploadResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *PrepareUploadResponse) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *PrepareUploadResponse) GetPayments() []*PaymentEntry {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *PrepareUploadResponse) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PrepareUploadResponse) GetPoolCommitments() []*PoolCommitmentEntry {
	if x != nil {
		return x.PoolCommitments
	}
	return nil
}

func (x *PrepareUploadResponse) GetMerklePaymentTimestamp() uint64 {
	if x != nil {
		return x.MerklePaymentTimestamp
	}
	return 0
}

func (x *PrepareUploadResponse) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *PrepareUploadResponse) GetPaymentVaultAddress() string {
	if x != nil {
		return x.PaymentVaultAddress
	}
	return ""
}

func (x *PrepareUploadResponse) GetPaymentTokenAddress() string {
	if x != nil {
		return x.PaymentTokenAddress
	}
	return ""
}

func (x *PrepareUploadResponse) GetRpcUrl() string {
	if x != nil {
		return x.RpcUrl
	}
	return ""
}

// A pool commitment entry for the merkle payment contract.
type PoolCommitmentEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pool hash (hex with 0x prefix, 32 bytes).
	PoolHash string `protobuf:"bytes,1,opt,name=pool_hash,json=poolHash,proto3" json:"pool_hash,omitempty"`
	// Exactly 16 candidate nodes.
	Candidates    []*CandidateNodeEntry `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolCommitmentEntry) Reset() {
	*x = PoolCommitmentEntry{}
	mi := &file_antd_v1_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolCommitmentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolCommitmentEntry) ProtoMessage() {}

func (x *PoolCommitmentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolCommitmentEntry.ProtoReflect.Descriptor instead.
func (*PoolCommitmentEntry) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{3}
}

func (x *PoolCommitmentEntry) GetPoolHash() string {
	if x != nil {
		return x.PoolHash
	}
	return ""
}

func (x *PoolCommitmentEntry) GetCandidates() []*CandidateNodeEntry {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// A candidate node: rewards address + price (amount).
type CandidateNodeEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node's rewards address (hex with 0x prefix, 20 bytes).
	RewardsAddress string `protobuf:"bytes,1,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	// Node's price as a decimal string (maps to the contract's `amount` field).
	Amount        string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateNodeEntry) Reset() {
	*x = CandidateNodeEntry{}
	mi := &file_antd_v1_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateNodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateNodeEntry) ProtoMessage() {}

func (x *CandidateNodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateNodeEntry.ProtoReflect.Descriptor instead.
func (*CandidateNodeEntry) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateNodeEntry) GetRewardsAddress() string {
	if x != nil {
		return x.RewardsAddress
	}
	return ""
}

func (x *CandidateNodeEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type FinalizeUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The upload_id returned from a Prepare* call.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Wave-batch: map of quote_hash (hex) → tx_hash (hex) from the on-chain
	// payment. Required when the prepared upload was wave-batch, must be
	// empty otherwise.
	TxHashes map[string]string `protobuf:"bytes,2,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Merkle: winner pool hash (hex with 0x prefix, 32 bytes) from the
	// `MerklePaymentMade` event. Required when the prepared upload was
	// merkle, must be empty otherwise.
	WinnerPoolHash string `protobuf:"bytes,3,opt,name=winner_pool_hash,json=winnerPoolHash,proto3" json:"winner_pool_hash,omitempty"`
	// If true, store the DataMap on-network via the daemon's internal wallet
	// and return its address. If false (default), return the raw DataMap
	// for caller-side storage. Equivalent to the REST `store_data_map`
	// field.
	StoreDataMap  bool `protobuf:"varint,4,opt,name=store_data_map,json=storeDataMap,proto3" json:"store_data_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadRequest) Reset() {
	*x = FinalizeUploadRequest{}
	mi := &file_antd_v1_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadRequest) ProtoMessage() {}

func (x *FinalizeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadRequest.ProtoReflect.Descriptor instead.
func (*FinalizeUploadRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizeUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *FinalizeUploadRequest) GetTxHashes() map[string]string {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

func (x *FinalizeUploadRequest) GetWinnerPoolHash() string {
	if x != nil {
		return x.WinnerPoolHash
	}
	return ""
}

func (x *FinalizeUploadRequest) GetStoreDataMap() bool {
	if x != nil {
		return x.StoreDataMap
	}
	return false
}

type FinalizeUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hex-encoded rmp_serde-serialized DataMap. Always returned.
	DataMap string `protobuf:"bytes,1,opt,name=data_map,json=dataMap,proto3" json:"data_map,omitempty"`
	// Network address of the stored DataMap, only set when the legacy
	// `store_data_map = true` path published the DataMap via the daemon's
	// internal wallet. New callers should prefer `visibility = "public"`
	// on prepare and read `data_map_address` instead.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Network address of the bundled DataMap chunk when the upload was
	// prepared with `visibility = "public"`. The DataMap chunk's payment
	// is part of the same external-signer batch as the data chunks, so
	// no separate daemon-wallet payment is required.
	DataMapAddress string `protobuf:"bytes,3,opt,name=data_map_address,json=dataMapAddress,proto3" json:"data_map_address,omitempty"`
	// Number of chunks stored on the network.
	ChunksStored  uint64 `protobuf:"varint,4,opt,name=chunks_stored,json=chunksStored,proto3" json:"chunks_stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadResponse) Reset() {
	*x = FinalizeUploadResponse{}
	mi := &file_antd_v1_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadResponse) ProtoMessage() {}

func (x *FinalizeUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadResponse.ProtoReflect.Descriptor instead.
func (*FinalizeUploadResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_upload_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeUploadResponse) GetDataMap() string {
	if x != nil {
		return x.DataMap
	}
	return ""
}

func (x *FinalizeUploadResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FinalizeUploadResponse) GetDataMapAddress() string {
	if x != nil {
		return x.DataMapAddress
	}
	return ""
}

func (x *FinalizeUploadResponse) GetChunksStored() uint64 {
	if x != nil {
		return x.ChunksStored
	}
	return 0
}

var File_antd_v1_upload_proto protoreflect.FileDescriptor

const file_antd_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/upload.proto\x12\aantd.v1\x1a\x14antd/v1/common.proto\"N\n" +
	"\x18PrepareFileUploadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\"N\n" +
	"\x18PrepareDataUploadRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\"\xc7\x03\n" +
	"\x15PrepareUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12!\n" +
	"\fpayment_type\x18\x02 \x01(\tR\vpaymentType\x121\n" +
	"\bpayments\x18\x03 \x03(\v2\x15.antd.v1.PaymentEntryR\bpayments\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\rR\x05depth\x12G\n" +
	"\x10pool_commitments\x18\x05 \x03(\v2\x1c.antd.v1.PoolCommitmentEntryR\x0fpoolCommitments\x128\n" +
	"\x18merkle_payment_timestamp\x18\x06 \x01(\x04R\x16merklePaymentTimestamp\x12!\n" +
	"\ftotal_amount\x18\a \x01(\tR\vtotalAmount\x122\n" +
	"\x15payment_vault_address\x18\b \x01(\tR\x13paymentVaultAddress\x122\n" +
	"\x15payment_token_address\x18\t \x01(\tR\x13paymentTokenAddress\x12\x17\n" +
	"\arpc_url\x18\n" +
	" \x01(\tR\x06rpcUrl\"o\n" +
	"\x13PoolCommitmentEntry\x12\x1b\n" +
	"\tpool_hash\x18\x01 \x01(\tR\bpoolHash\x12;\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x1b.antd.v1.CandidateNodeEntryR\n" +
	"candidates\"U\n" +
	"\x12CandidateNodeEntry\x12'\n" +
	"\x0frewards_address\x18\x01 \x01(\tR\x0erewardsAddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\x8c\x02\n" +
	"\x15FinalizeUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12I\n" +
	"\ttx_hashes\x18\x02 \x03(\v2,.antd.v1.FinalizeUploadRequest.TxHashesEntryR\btxHashes\x12(\n" +
	"\x10winner_pool_hash\x18\x03 \x01(\tR\x0ewinnerPoolHash\x12$\n" +
	"\x0estore_data_map\x18\x04 \x01(\bR\fstoreDataMap\x1a;\n" +
	"\rTxHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x16FinalizeUploadResponse\x12\x19\n" +
	"\bdata_map\x18\x01 \x01(\tR\adataMap\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12(\n" +
	"\x10data_map_address\x18\x03 \x01(\tR\x0edataMapAddress\x12#\n" +
	"\rchunks_stored\x18\x04 \x01(\x04R\fchunksStored2\x92\x02\n" +
	"\rUploadService\x12V\n" +
	"\x11PrepareFileUpload\x12!.antd.v1.PrepareFileUploadRequest\x1a\x1e.antd.v1.PrepareUploadResponse\x12V\n" +
	"\x11PrepareDataUpload\x12!.antd.v1.PrepareDataUploadRequest\x1a\x1e.antd.v1.PrepareUploadResponse\x12Q\n" +
	"\x0eFinalizeUpload\x12\x1e.antd.v1.FinalizeUploadRequest\x1a\x1f.antd.v1.FinalizeUploadResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_upload_proto_rawDescOnce sync.Once
	file_antd_v1_upload_proto_rawDescData []byte
)

func file_antd_v1_upload_proto_rawDescGZIP() []byte {
	file_antd_v1_upload_proto_rawDescOnce.Do(func() {
		file_antd_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_upload_proto_rawDesc), len(file_antd_v1_upload_proto_rawDesc)))
	})
	return file_antd_v1_upload_proto_rawDescData
}

var file_antd_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_antd_v1_upload_proto_goTypes = []any{
	(*PrepareFileUploadRequest)(nil), // 0: antd.v1.PrepareFileUploadRequest
	(*PrepareDataUploadRequest)(nil), // 1: antd.v1.PrepareDataUploadRequest
	(*PrepareUploadResponse)(nil),    // 2: antd.v1.PrepareUploadResponse
	(*PoolCommitmentEntry)(nil),      // 3: antd.v1.PoolCommitmentEntry
	(*CandidateNodeEntry)(nil),       // 4: antd.v1.CandidateNodeEntry
	(*FinalizeUploadRequest)(nil),    // 5: antd.v1.FinalizeUploadRequest
	(*FinalizeUploadResponse)(nil),   // 6: antd.v1.FinalizeUploadResponse
	nil,                              // 7: antd.v1.FinalizeUploadRequest.TxHashesEntry
	(*PaymentEntry)(nil),             // 8: antd.v1.PaymentEntry
}
var file_antd_v1_upload_proto_depIdxs = []int32{
	8, // 0: antd.v1.PrepareUploadResponse.payments:type_name -> antd.v1.PaymentEntry
	3, // 1: antd.v1.PrepareUploadResponse.pool_commitments:type_name -> antd.v1.PoolCommitmentEntry
	4, // 2: antd.v1.PoolCommitmentEntry.candidates:type_name -> antd.v1.CandidateNodeEntry
	7, // 3: antd.v1.FinalizeUploadRequest.tx_hashes:type_name -> antd.v1.FinalizeUploadRequest.TxHashesEntry
	0, // 4: antd.v1.UploadService.PrepareFileUpload:input_type -> antd.v1.PrepareFileUploadRequest
	1, // 5: antd.v1.UploadService.PrepareDataUpload:input_type -> antd.v1.PrepareDataUploadRequest
	5, // 6: antd.v1.UploadService.FinalizeUpload:input_type -> antd.v1.FinalizeUploadRequest
	2, // 7: antd.v1.UploadService.PrepareFileUpload:output_type -> antd.v1.PrepareUploadResponse
	2, // 8: antd.v1.UploadService.PrepareDataUpload:output_type -> antd.v1.PrepareUploadResponse
	6, // 9: antd.v1.UploadService.FinalizeUpload:output_type -> antd.v1.FinalizeUploadResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_antd_v1_upload_proto_init() }
func file_antd_v1_upload_proto_init() {
	if File_antd_v1_upload_proto != nil {
		return
	}
	file_antd_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_upload_proto_rawDesc), len(file_antd_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_upload_proto_goTypes,
		DependencyIndexes: file_antd_v1_upload_proto_depIdxs,
		MessageInfos:      file_antd_v1_upload_proto_msgTypes,
	}.Build()
	File_antd_v1_upload_proto = out.File
	file_antd_v1_upload_proto_goTypes = nil
	file_antd_v1_upload_proto_depIdxs = nil
}
