// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: antd/v1/verify.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyQuotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max 1024 entries per call (each entry costs one or two ML-DSA-65
	// verifications).
	Entries       []*VerifyQuoteEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyQuotesRequest) Reset() {
	*x = VerifyQuotesRequest{}
	mi := &file_antd_v1_verify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQuotesRequest) ProtoMessage() {}

func (x *VerifyQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_verify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQuotesRequest.ProtoReflect.Descriptor instead.
func (*VerifyQuotesRequest) Descriptor() ([]byte, []int) {
	return file_antd_v1_verify_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyQuotesRequest) GetEntries() []*VerifyQuoteEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// One entry to verify: the payment triple the caller was asked to pay plus
// the opaque signed artifacts from the prepare response's `signed_quotes`.
type VerifyQuoteEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quote hash the payer was asked to pay (hex with 0x prefix, 32 bytes).
	QuoteHash string `protobuf:"bytes,1,opt,name=quote_hash,json=quoteHash,proto3" json:"quote_hash,omitempty"`
	// Rewards address the payer was asked to pay (hex with 0x prefix).
	RewardsAddress string `protobuf:"bytes,2,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	// Amount the payer was asked to pay (atto tokens as decimal string).
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// msgpack-serialized signed PaymentQuote — from SignedQuoteEntry.quote.
	SignedQuote []byte `protobuf:"bytes,4,opt,name=signed_quote,json=signedQuote,proto3" json:"signed_quote,omitempty"`
	// msgpack-serialized StorageCommitment sidecar — from
	// SignedQuoteEntry.commitment_sidecar. Required when the quote is
	// commitment-bound; empty otherwise.
	CommitmentSidecar []byte `protobuf:"bytes,5,opt,name=commitment_sidecar,json=commitmentSidecar,proto3" json:"commitment_sidecar,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyQuoteEntry) Reset() {
	*x = VerifyQuoteEntry{}
	mi := &file_antd_v1_verify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQuoteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQuoteEntry) ProtoMessage() {}

func (x *VerifyQuoteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_verify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQuoteEntry.ProtoReflect.Descriptor instead.
func (*VerifyQuoteEntry) Descriptor() ([]byte, []int) {
	return file_antd_v1_verify_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyQuoteEntry) GetQuoteHash() string {
	if x != nil {
		return x.QuoteHash
	}
	return ""
}

func (x *VerifyQuoteEntry) GetRewardsAddress() string {
	if x != nil {
		return x.RewardsAddress
	}
	return ""
}

func (x *VerifyQuoteEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *VerifyQuoteEntry) GetSignedQuote() []byte {
	if x != nil {
		return x.SignedQuote
	}
	return nil
}

func (x *VerifyQuoteEntry) GetCommitmentSidecar() []byte {
	if x != nil {
		return x.CommitmentSidecar
	}
	return nil
}

type VerifyQuotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True only when `entries` is non-empty and every entry verified.
	Valid         bool                  `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Entries       []*VerifyQuoteVerdict `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyQuotesResponse) Reset() {
	*x = VerifyQuotesResponse{}
	mi := &file_antd_v1_verify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQuotesResponse) ProtoMessage() {}

func (x *VerifyQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_verify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQuotesResponse.ProtoReflect.Descriptor instead.
func (*VerifyQuotesResponse) Descriptor() ([]byte, []int) {
	return file_antd_v1_verify_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyQuotesResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyQuotesResponse) GetEntries() []*VerifyQuoteVerdict {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Per-entry verdict. The extracted fields are populated as soon as the signed
// quote deserializes — even when a later check fails — so policy layers can
// see what the quote claimed. They are meaningless while `quote_decoded` is
// false.
type VerifyQuoteVerdict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of the request entry's quote_hash.
	QuoteHash string `protobuf:"bytes,1,opt,name=quote_hash,json=quoteHash,proto3" json:"quote_hash,omitempty"`
	// True when every check passed.
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	// The first failing rule, by name. Empty when valid.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// True once the signed quote deserialized (the extracted fields below are
	// populated).
	QuoteDecoded bool `protobuf:"varint,4,opt,name=quote_decoded,json=quoteDecoded,proto3" json:"quote_decoded,omitempty"`
	// Quote timestamp (unix seconds) — for the caller's expiry policy.
	TimestampUnixSecs uint64 `protobuf:"varint,5,opt,name=timestamp_unix_secs,json=timestampUnixSecs,proto3" json:"timestamp_unix_secs,omitempty"`
	// The chunk address the quote covers (hex, 32 bytes) — for the caller's
	// chunk-set equality policy.
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// The signed price (atto tokens as decimal string).
	Price string `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	// The signed rewards address (hex with 0x prefix).
	RewardsAddress string `protobuf:"bytes,8,opt,name=rewards_address,json=rewardsAddress,proto3" json:"rewards_address,omitempty"`
	// Claimed ADR-0004 storage-commitment key count (0 = baseline quote) — for
	// the caller's count-plausibility cap.
	CommittedKeyCount uint32 `protobuf:"varint,9,opt,name=committed_key_count,json=committedKeyCount,proto3" json:"committed_key_count,omitempty"`
	// Whether the quote pins a storage commitment.
	Pinned        bool `protobuf:"varint,10,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyQuoteVerdict) Reset() {
	*x = VerifyQuoteVerdict{}
	mi := &file_antd_v1_verify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQuoteVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQuoteVerdict) ProtoMessage() {}

func (x *VerifyQuoteVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_antd_v1_verify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQuoteVerdict.ProtoReflect.Descriptor instead.
func (*VerifyQuoteVerdict) Descriptor() ([]byte, []int) {
	return file_antd_v1_verify_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyQuoteVerdict) GetQuoteHash() string {
	if x != nil {
		return x.QuoteHash
	}
	return ""
}

func (x *VerifyQuoteVerdict) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyQuoteVerdict) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VerifyQuoteVerdict) GetQuoteDecoded() bool {
	if x != nil {
		return x.QuoteDecoded
	}
	return false
}

func (x *VerifyQuoteVerdict) GetTimestampUnixSecs() uint64 {
	if x != nil {
		return x.TimestampUnixSecs
	}
	return 0
}

func (x *VerifyQuoteVerdict) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VerifyQuoteVerdict) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *VerifyQuoteVerdict) GetRewardsAddress() string {
	if x != nil {
		return x.RewardsAddress
	}
	return ""
}

func (x *VerifyQuoteVerdict) GetCommittedKeyCount() uint32 {
	if x != nil {
		return x.CommittedKeyCount
	}
	return 0
}

func (x *VerifyQuoteVerdict) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

var File_antd_v1_verify_proto protoreflect.FileDescriptor

const file_antd_v1_verify_proto_rawDesc = "" +
	"\n" +
	"\x14antd/v1/verify.proto\x12\aantd.v1\"J\n" +
	"\x13VerifyQuotesRequest\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.antd.v1.VerifyQuoteEntryR\aentries\"\xc4\x01\n" +
	"\x10VerifyQuoteEntry\x12\x1d\n" +
	"\n" +
	"quote_hash\x18\x01 \x01(\tR\tquoteHash\x12'\n" +
	"\x0frewards_address\x18\x02 \x01(\tR\x0erewardsAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12!\n" +
	"\fsigned_quote\x18\x04 \x01(\fR\vsignedQuote\x12-\n" +
	"\x12commitment_sidecar\x18\x05 \x01(\fR\x11commitmentSidecar\"c\n" +
	"\x14VerifyQuotesResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.antd.v1.VerifyQuoteVerdictR\aentries\"\xd5\x02\n" +
	"\x12VerifyQuoteVerdict\x12\x1d\n" +
	"\n" +
	"quote_hash\x18\x01 \x01(\tR\tquoteHash\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12#\n" +
	"\rquote_decoded\x18\x04 \x01(\bR\fquoteDecoded\x12.\n" +
	"\x13timestamp_unix_secs\x18\x05 \x01(\x04R\x11timestampUnixSecs\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12'\n" +
	"\x0frewards_address\x18\b \x01(\tR\x0erewardsAddress\x12.\n" +
	"\x13committed_key_count\x18\t \x01(\rR\x11committedKeyCount\x12\x16\n" +
	"\x06pinned\x18\n" +
	" \x01(\bR\x06pinned2\\\n" +
	"\rVerifyService\x12K\n" +
	"\fVerifyQuotes\x12\x1c.antd.v1.VerifyQuotesRequest\x1a\x1d.antd.v1.VerifyQuotesResponseBDZ8github.com/WithAutonomi/ant-sdk/antd-go/proto/antd/v1;v1\xaa\x02\aAntd.V1b\x06proto3"

var (
	file_antd_v1_verify_proto_rawDescOnce sync.Once
	file_antd_v1_verify_proto_rawDescData []byte
)

func file_antd_v1_verify_proto_rawDescGZIP() []byte {
	file_antd_v1_verify_proto_rawDescOnce.Do(func() {
		file_antd_v1_verify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antd_v1_verify_proto_rawDesc), len(file_antd_v1_verify_proto_rawDesc)))
	})
	return file_antd_v1_verify_proto_rawDescData
}

var file_antd_v1_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_antd_v1_verify_proto_goTypes = []any{
	(*VerifyQuotesRequest)(nil),  // 0: antd.v1.VerifyQuotesRequest
	(*VerifyQuoteEntry)(nil),     // 1: antd.v1.VerifyQuoteEntry
	(*VerifyQuotesResponse)(nil), // 2: antd.v1.VerifyQuotesResponse
	(*VerifyQuoteVerdict)(nil),   // 3: antd.v1.VerifyQuoteVerdict
}
var file_antd_v1_verify_proto_depIdxs = []int32{
	1, // 0: antd.v1.VerifyQuotesRequest.entries:type_name -> antd.v1.VerifyQuoteEntry
	3, // 1: antd.v1.VerifyQuotesResponse.entries:type_name -> antd.v1.VerifyQuoteVerdict
	0, // 2: antd.v1.VerifyService.VerifyQuotes:input_type -> antd.v1.VerifyQuotesRequest
	2, // 3: antd.v1.VerifyService.VerifyQuotes:output_type -> antd.v1.VerifyQuotesResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_antd_v1_verify_proto_init() }
func file_antd_v1_verify_proto_init() {
	if File_antd_v1_verify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antd_v1_verify_proto_rawDesc), len(file_antd_v1_verify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antd_v1_verify_proto_goTypes,
		DependencyIndexes: file_antd_v1_verify_proto_depIdxs,
		MessageInfos:      file_antd_v1_verify_proto_msgTypes,
	}.Build()
	File_antd_v1_verify_proto = out.File
	file_antd_v1_verify_proto_goTypes = nil
	file_antd_v1_verify_proto_depIdxs = nil
}
