// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: antd/v1/verify.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerifyService_VerifyQuotes_FullMethodName = "/antd.v1.VerifyService/VerifyQuotes"
)

// VerifyServiceClient is the client API for VerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stateless offline verification of signed payment quotes (hosted payments,
// V2-854). Pure function of the request: no network, no wallet, no session
// state. Run by "the party about to pay" — in hosted mode, the payment
// gateway calls it on its own antd instance (never the customer's) before
// paying a batch.
//
// Checks per entry: quote-hash recomputation, ML-DSA-65 signature,
// paid-fields equality against the request triple, and the ADR-0004
// resolve-before-pay commitment binding with exact on-curve pricing
// (`price == calculate_price(committed_key_count)`; baseline quotes must
// price exactly `calculate_price(0)`). Policy checks (expiry windows, replay
// ledgers, chunk-set equality, count-plausibility caps) stay caller-side —
// the verdicts carry the extracted fields those policies need.
type VerifyServiceClient interface {
	VerifyQuotes(ctx context.Context, in *VerifyQuotesRequest, opts ...grpc.CallOption) (*VerifyQuotesResponse, error)
}

type verifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyServiceClient(cc grpc.ClientConnInterface) VerifyServiceClient {
	return &verifyServiceClient{cc}
}

func (c *verifyServiceClient) VerifyQuotes(ctx context.Context, in *VerifyQuotesRequest, opts ...grpc.CallOption) (*VerifyQuotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyQuotesResponse)
	err := c.cc.Invoke(ctx, VerifyService_VerifyQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyServiceServer is the server API for VerifyService service.
// All implementations must embed UnimplementedVerifyServiceServer
// for forward compatibility.
//
// Stateless offline verification of signed payment quotes (hosted payments,
// V2-854). Pure function of the request: no network, no wallet, no session
// state. Run by "the party about to pay" — in hosted mode, the payment
// gateway calls it on its own antd instance (never the customer's) before
// paying a batch.
//
// Checks per entry: quote-hash recomputation, ML-DSA-65 signature,
// paid-fields equality against the request triple, and the ADR-0004
// resolve-before-pay commitment binding with exact on-curve pricing
// (`price == calculate_price(committed_key_count)`; baseline quotes must
// price exactly `calculate_price(0)`). Policy checks (expiry windows, replay
// ledgers, chunk-set equality, count-plausibility caps) stay caller-side —
// the verdicts carry the extracted fields those policies need.
type VerifyServiceServer interface {
	VerifyQuotes(context.Context, *VerifyQuotesRequest) (*VerifyQuotesResponse, error)
	mustEmbedUnimplementedVerifyServiceServer()
}

// UnimplementedVerifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifyServiceServer struct{}

func (UnimplementedVerifyServiceServer) VerifyQuotes(context.Context, *VerifyQuotesRequest) (*VerifyQuotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyQuotes not implemented")
}
func (UnimplementedVerifyServiceServer) mustEmbedUnimplementedVerifyServiceServer() {}
func (UnimplementedVerifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeVerifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyServiceServer will
// result in compilation errors.
type UnsafeVerifyServiceServer interface {
	mustEmbedUnimplementedVerifyServiceServer()
}

func RegisterVerifyServiceServer(s grpc.ServiceRegistrar, srv VerifyServiceServer) {
	// If the following call panics, it indicates UnimplementedVerifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerifyService_ServiceDesc, srv)
}

func _VerifyService_VerifyQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServiceServer).VerifyQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyService_VerifyQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServiceServer).VerifyQuotes(ctx, req.(*VerifyQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyService_ServiceDesc is the grpc.ServiceDesc for VerifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antd.v1.VerifyService",
	HandlerType: (*VerifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyQuotes",
			Handler:    _VerifyService_VerifyQuotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antd/v1/verify.proto",
}
