"""Python bindings for the Autonomi FFI (direct-network, daemon-less client).

Generated by UniFFI from the `ant-ffi` Rust crate; re-exports the full
generated surface (Client, Wallet, external-signer flow, records/objects).
The native library (libant_ffi.dylib / .so / ant_ffi.dll) is bundled alongside
this module and loaded automatically.
"""

from .ant_ffi import *  # noqa: F401,F403
from .ant_ffi import ant_ffi_version  # noqa: F401
